/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminUserEntitlementResponse
 */
export interface AdminUserEntitlementResponse {
    /**
     *
     * @type {string}
     * @memberof AdminUserEntitlementResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserEntitlementResponse
     */
    message: string;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof AdminUserEntitlementResponse
     */
    data: { [key: string]: any; };
    /**
     *
     * @type {string}
     * @memberof AdminUserEntitlementResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AdminUserEntitlementResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AdminUserEntitlementResponse interface.
 */
export function instanceOfAdminUserEntitlementResponse(value: object): value is AdminUserEntitlementResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AdminUserEntitlementResponseFromJSON(json: any): AdminUserEntitlementResponse {
    return AdminUserEntitlementResponseFromJSONTyped(json, false);
}

export function AdminUserEntitlementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserEntitlementResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': json['data'],
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AdminUserEntitlementResponseToJSON(json: any): AdminUserEntitlementResponse {
    return AdminUserEntitlementResponseToJSONTyped(json, false);
}

export function AdminUserEntitlementResponseToJSONTyped(value?: AdminUserEntitlementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
