/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminUserSecurityResetRequest
 */
export interface AdminUserSecurityResetRequest {
    /**
     *
     * @type {string}
     * @memberof AdminUserSecurityResetRequest
     */
    auditReason: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserSecurityResetRequest
     */
    confirmationUserId: string;
}

/**
 * Check if a given object implements the AdminUserSecurityResetRequest interface.
 */
export function instanceOfAdminUserSecurityResetRequest(value: object): value is AdminUserSecurityResetRequest {
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    if (!('confirmationUserId' in value) || value['confirmationUserId'] === undefined) return false;
    return true;
}

export function AdminUserSecurityResetRequestFromJSON(json: any): AdminUserSecurityResetRequest {
    return AdminUserSecurityResetRequestFromJSONTyped(json, false);
}

export function AdminUserSecurityResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserSecurityResetRequest {
    if (json == null) {
        return json;
    }
    return {

        'auditReason': json['auditReason'],
        'confirmationUserId': json['confirmationUserId'],
    };
}

export function AdminUserSecurityResetRequestToJSON(json: any): AdminUserSecurityResetRequest {
    return AdminUserSecurityResetRequestToJSONTyped(json, false);
}

export function AdminUserSecurityResetRequestToJSONTyped(value?: AdminUserSecurityResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'auditReason': value['auditReason'],
        'confirmationUserId': value['confirmationUserId'],
    };
}
