/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminUserProfileRequest
 */
export interface AdminUserProfileRequest {
    /**
     *
     * @type {string}
     * @memberof AdminUserProfileRequest
     */
    nickname?: string | null;
    /**
     *
     * @type {string}
     * @memberof AdminUserProfileRequest
     */
    avatarUrl?: string | null;
    /**
     *
     * @type {string}
     * @memberof AdminUserProfileRequest
     */
    locale: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserProfileRequest
     */
    timeZone: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserProfileRequest
     */
    auditReason: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserProfileRequest
     */
    confirmationUserId: string;
}

/**
 * Check if a given object implements the AdminUserProfileRequest interface.
 */
export function instanceOfAdminUserProfileRequest(value: object): value is AdminUserProfileRequest {
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('timeZone' in value) || value['timeZone'] === undefined) return false;
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    if (!('confirmationUserId' in value) || value['confirmationUserId'] === undefined) return false;
    return true;
}

export function AdminUserProfileRequestFromJSON(json: any): AdminUserProfileRequest {
    return AdminUserProfileRequestFromJSONTyped(json, false);
}

export function AdminUserProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserProfileRequest {
    if (json == null) {
        return json;
    }
    return {

        'nickname': json['nickname'] === undefined ? undefined : json['nickname'] === null ? null : json['nickname'],
        'avatarUrl': json['avatarUrl'] === undefined ? undefined : json['avatarUrl'] === null ? null : json['avatarUrl'],
        'locale': json['locale'],
        'timeZone': json['timeZone'],
        'auditReason': json['auditReason'],
        'confirmationUserId': json['confirmationUserId'],
    };
}

export function AdminUserProfileRequestToJSON(json: any): AdminUserProfileRequest {
    return AdminUserProfileRequestToJSONTyped(json, false);
}

export function AdminUserProfileRequestToJSONTyped(value?: AdminUserProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'nickname': value['nickname'],
        'avatarUrl': value['avatarUrl'],
        'locale': value['locale'],
        'timeZone': value['timeZone'],
        'auditReason': value['auditReason'],
        'confirmationUserId': value['confirmationUserId'],
    };
}
