/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const AdminMfaStatus = {
    Enrolled: 'ENROLLED',
    ResetRequired: 'RESET_REQUIRED'
} as const;
export type AdminMfaStatus = typeof AdminMfaStatus[keyof typeof AdminMfaStatus];


export function instanceOfAdminMfaStatus(value: any): boolean {
    for (const key in AdminMfaStatus) {
        if (Object.prototype.hasOwnProperty.call(AdminMfaStatus, key)) {
            if (AdminMfaStatus[key as keyof typeof AdminMfaStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AdminMfaStatusFromJSON(json: any): AdminMfaStatus {
    return AdminMfaStatusFromJSONTyped(json, false);
}

export function AdminMfaStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminMfaStatus {
    return json as AdminMfaStatus;
}

export function AdminMfaStatusToJSON(value?: AdminMfaStatus | null): any {
    return value as any;
}

export function AdminMfaStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AdminMfaStatus {
    return value as AdminMfaStatus;
}
