/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminUserPlanGrantRequest
 */
export interface AdminUserPlanGrantRequest {
    /**
     *
     * @type {string}
     * @memberof AdminUserPlanGrantRequest
     */
    productVersionId: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserPlanGrantRequest
     */
    auditReason: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserPlanGrantRequest
     */
    confirmationUserId: string;
}

/**
 * Check if a given object implements the AdminUserPlanGrantRequest interface.
 */
export function instanceOfAdminUserPlanGrantRequest(value: object): value is AdminUserPlanGrantRequest {
    if (!('productVersionId' in value) || value['productVersionId'] === undefined) return false;
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    if (!('confirmationUserId' in value) || value['confirmationUserId'] === undefined) return false;
    return true;
}

export function AdminUserPlanGrantRequestFromJSON(json: any): AdminUserPlanGrantRequest {
    return AdminUserPlanGrantRequestFromJSONTyped(json, false);
}

export function AdminUserPlanGrantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserPlanGrantRequest {
    if (json == null) {
        return json;
    }
    return {

        'productVersionId': json['productVersionId'],
        'auditReason': json['auditReason'],
        'confirmationUserId': json['confirmationUserId'],
    };
}

export function AdminUserPlanGrantRequestToJSON(json: any): AdminUserPlanGrantRequest {
    return AdminUserPlanGrantRequestToJSONTyped(json, false);
}

export function AdminUserPlanGrantRequestToJSONTyped(value?: AdminUserPlanGrantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'productVersionId': value['productVersionId'],
        'auditReason': value['auditReason'],
        'confirmationUserId': value['confirmationUserId'],
    };
}
