/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminRefundListData } from './AdminRefundListData';
import {
    AdminRefundListDataFromJSON,
    AdminRefundListDataFromJSONTyped,
    AdminRefundListDataToJSON,
    AdminRefundListDataToJSONTyped,
} from './AdminRefundListData';

/**
 *
 * @export
 * @interface AdminRefundListResponse
 */
export interface AdminRefundListResponse {
    /**
     *
     * @type {string}
     * @memberof AdminRefundListResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AdminRefundListResponse
     */
    message: string;
    /**
     *
     * @type {AdminRefundListData}
     * @memberof AdminRefundListResponse
     */
    data: AdminRefundListData;
    /**
     *
     * @type {string}
     * @memberof AdminRefundListResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AdminRefundListResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AdminRefundListResponse interface.
 */
export function instanceOfAdminRefundListResponse(value: object): value is AdminRefundListResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AdminRefundListResponseFromJSON(json: any): AdminRefundListResponse {
    return AdminRefundListResponseFromJSONTyped(json, false);
}

export function AdminRefundListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRefundListResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AdminRefundListDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AdminRefundListResponseToJSON(json: any): AdminRefundListResponse {
    return AdminRefundListResponseToJSONTyped(json, false);
}

export function AdminRefundListResponseToJSONTyped(value?: AdminRefundListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AdminRefundListDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
