/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminMfaMethod } from './AdminMfaMethod';
import {
    AdminMfaMethodFromJSON,
    AdminMfaMethodFromJSONTyped,
    AdminMfaMethodToJSON,
    AdminMfaMethodToJSONTyped,
} from './AdminMfaMethod';

/**
 *
 * @export
 * @interface AdminMfaChallenge
 */
export interface AdminMfaChallenge {
    /**
     *
     * @type {string}
     * @memberof AdminMfaChallenge
     */
    challengeId: string;
    /**
     *
     * @type {Set<AdminMfaMethod>}
     * @memberof AdminMfaChallenge
     */
    allowedMethods: Set<AdminMfaMethod>;
    /**
     *
     * @type {Date}
     * @memberof AdminMfaChallenge
     */
    expiresAt: Date;
    /**
     *
     * @type {number}
     * @memberof AdminMfaChallenge
     */
    attemptsRemaining: number;
}

/**
 * Check if a given object implements the AdminMfaChallenge interface.
 */
export function instanceOfAdminMfaChallenge(value: object): value is AdminMfaChallenge {
    if (!('challengeId' in value) || value['challengeId'] === undefined) return false;
    if (!('allowedMethods' in value) || value['allowedMethods'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('attemptsRemaining' in value) || value['attemptsRemaining'] === undefined) return false;
    return true;
}

export function AdminMfaChallengeFromJSON(json: any): AdminMfaChallenge {
    return AdminMfaChallengeFromJSONTyped(json, false);
}

export function AdminMfaChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminMfaChallenge {
    if (json == null) {
        return json;
    }
    return {

        'challengeId': json['challengeId'],
        'allowedMethods': (new Set((json['allowedMethods'] as Array<any>).map(AdminMfaMethodFromJSON))),
        'expiresAt': (new Date(json['expiresAt'])),
        'attemptsRemaining': json['attemptsRemaining'],
    };
}

export function AdminMfaChallengeToJSON(json: any): AdminMfaChallenge {
    return AdminMfaChallengeToJSONTyped(json, false);
}

export function AdminMfaChallengeToJSONTyped(value?: AdminMfaChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'challengeId': value['challengeId'],
        'allowedMethods': (Array.from(value['allowedMethods'] as Set<any>).map(AdminMfaMethodToJSON)),
        'expiresAt': value['expiresAt'].toISOString(),
        'attemptsRemaining': value['attemptsRemaining'],
    };
}
