/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOrder } from './AdminOrder';
import {
    AdminOrderFromJSON,
    AdminOrderFromJSONTyped,
    AdminOrderToJSON,
    AdminOrderToJSONTyped,
} from './AdminOrder';

/**
 *
 * @export
 * @interface AdminOrderResponse
 */
export interface AdminOrderResponse {
    /**
     *
     * @type {string}
     * @memberof AdminOrderResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AdminOrderResponse
     */
    message: string;
    /**
     *
     * @type {AdminOrder}
     * @memberof AdminOrderResponse
     */
    data: AdminOrder;
    /**
     *
     * @type {string}
     * @memberof AdminOrderResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AdminOrderResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AdminOrderResponse interface.
 */
export function instanceOfAdminOrderResponse(value: object): value is AdminOrderResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AdminOrderResponseFromJSON(json: any): AdminOrderResponse {
    return AdminOrderResponseFromJSONTyped(json, false);
}

export function AdminOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrderResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AdminOrderFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AdminOrderResponseToJSON(json: any): AdminOrderResponse {
    return AdminOrderResponseToJSONTyped(json, false);
}

export function AdminOrderResponseToJSONTyped(value?: AdminOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AdminOrderToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
