/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminRefund } from './AdminRefund';
import {
    AdminRefundFromJSON,
    AdminRefundFromJSONTyped,
    AdminRefundToJSON,
    AdminRefundToJSONTyped,
} from './AdminRefund';

/**
 *
 * @export
 * @interface AdminRefundListData
 */
export interface AdminRefundListData {
    /**
     *
     * @type {Array<AdminRefund>}
     * @memberof AdminRefundListData
     */
    items: Array<AdminRefund>;
    /**
     *
     * @type {string}
     * @memberof AdminRefundListData
     */
    nextCursor: string | null;
    /**
     *
     * @type {boolean}
     * @memberof AdminRefundListData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the AdminRefundListData interface.
 */
export function instanceOfAdminRefundListData(value: object): value is AdminRefundListData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function AdminRefundListDataFromJSON(json: any): AdminRefundListData {
    return AdminRefundListDataFromJSONTyped(json, false);
}

export function AdminRefundListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRefundListData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(AdminRefundFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function AdminRefundListDataToJSON(json: any): AdminRefundListData {
    return AdminRefundListDataToJSONTyped(json, false);
}

export function AdminRefundListDataToJSONTyped(value?: AdminRefundListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(AdminRefundToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
