/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminUserStatusRequest
 */
export interface AdminUserStatusRequest {
    /**
     *
     * @type {AdminUserStatusRequestStatusEnum}
     * @memberof AdminUserStatusRequest
     */
    status: AdminUserStatusRequestStatusEnum;
    /**
     *
     * @type {string}
     * @memberof AdminUserStatusRequest
     */
    auditReason: string;
    /**
     *
     * @type {string}
     * @memberof AdminUserStatusRequest
     */
    confirmationUserId: string;
}


/**
 * @export
 */
export const AdminUserStatusRequestStatusEnum = {
    Active: 'ACTIVE',
    Suspended: 'SUSPENDED'
} as const;
export type AdminUserStatusRequestStatusEnum = typeof AdminUserStatusRequestStatusEnum[keyof typeof AdminUserStatusRequestStatusEnum];


/**
 * Check if a given object implements the AdminUserStatusRequest interface.
 */
export function instanceOfAdminUserStatusRequest(value: object): value is AdminUserStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    if (!('confirmationUserId' in value) || value['confirmationUserId'] === undefined) return false;
    return true;
}

export function AdminUserStatusRequestFromJSON(json: any): AdminUserStatusRequest {
    return AdminUserStatusRequestFromJSONTyped(json, false);
}

export function AdminUserStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserStatusRequest {
    if (json == null) {
        return json;
    }
    return {

        'status': json['status'],
        'auditReason': json['auditReason'],
        'confirmationUserId': json['confirmationUserId'],
    };
}

export function AdminUserStatusRequestToJSON(json: any): AdminUserStatusRequest {
    return AdminUserStatusRequestToJSONTyped(json, false);
}

export function AdminUserStatusRequestToJSONTyped(value?: AdminUserStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status': value['status'],
        'auditReason': value['auditReason'],
        'confirmationUserId': value['confirmationUserId'],
    };
}
