/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const AdminAccountStatus = {
    Active: 'ACTIVE',
    Suspended: 'SUSPENDED',
    Disabled: 'DISABLED'
} as const;
export type AdminAccountStatus = typeof AdminAccountStatus[keyof typeof AdminAccountStatus];


export function instanceOfAdminAccountStatus(value: any): boolean {
    for (const key in AdminAccountStatus) {
        if (Object.prototype.hasOwnProperty.call(AdminAccountStatus, key)) {
            if (AdminAccountStatus[key as keyof typeof AdminAccountStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AdminAccountStatusFromJSON(json: any): AdminAccountStatus {
    return AdminAccountStatusFromJSONTyped(json, false);
}

export function AdminAccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAccountStatus {
    return json as AdminAccountStatus;
}

export function AdminAccountStatusToJSON(value?: AdminAccountStatus | null): any {
    return value as any;
}

export function AdminAccountStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AdminAccountStatus {
    return value as AdminAccountStatus;
}
