/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminTokenPair
 */
export interface AdminTokenPair {
    /**
     *
     * @type {AdminTokenPairTokenTypeEnum}
     * @memberof AdminTokenPair
     */
    tokenType: AdminTokenPairTokenTypeEnum;
    /**
     *
     * @type {string}
     * @memberof AdminTokenPair
     */
    accessToken: string;
    /**
     *
     * @type {Date}
     * @memberof AdminTokenPair
     */
    accessTokenExpiresAt: Date;
    /**
     * Single-use token. Presenting it rotates and revokes it.
     * @type {string}
     * @memberof AdminTokenPair
     */
    refreshToken: string;
    /**
     *
     * @type {Date}
     * @memberof AdminTokenPair
     */
    refreshTokenExpiresAt: Date;
}


/**
 * @export
 */
export const AdminTokenPairTokenTypeEnum = {
    Bearer: 'Bearer'
} as const;
export type AdminTokenPairTokenTypeEnum = typeof AdminTokenPairTokenTypeEnum[keyof typeof AdminTokenPairTokenTypeEnum];


/**
 * Check if a given object implements the AdminTokenPair interface.
 */
export function instanceOfAdminTokenPair(value: object): value is AdminTokenPair {
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (value['tokenType'] !== 'Bearer') return false;

    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('accessTokenExpiresAt' in value) || value['accessTokenExpiresAt'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('refreshTokenExpiresAt' in value) || value['refreshTokenExpiresAt'] === undefined) return false;
    return true;
}

export function AdminTokenPairFromJSON(json: any): AdminTokenPair {
    return AdminTokenPairFromJSONTyped(json, false);
}

export function AdminTokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminTokenPair {
    if (json == null) {
        return json;
    }
    return {

        'tokenType': json['tokenType'],
        'accessToken': json['accessToken'],
        'accessTokenExpiresAt': (new Date(json['accessTokenExpiresAt'])),
        'refreshToken': json['refreshToken'],
        'refreshTokenExpiresAt': (new Date(json['refreshTokenExpiresAt'])),
    };
}

export function AdminTokenPairToJSON(json: any): AdminTokenPair {
    return AdminTokenPairToJSONTyped(json, false);
}

export function AdminTokenPairToJSONTyped(value?: AdminTokenPair | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'tokenType': value['tokenType'],
        'accessToken': value['accessToken'],
        'accessTokenExpiresAt': value['accessTokenExpiresAt'].toISOString(),
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'].toISOString(),
    };
}
