/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminOrder } from './AdminOrder';
import {
    AdminOrderFromJSON,
    AdminOrderFromJSONTyped,
    AdminOrderToJSON,
    AdminOrderToJSONTyped,
} from './AdminOrder';

/**
 *
 * @export
 * @interface AdminOrderListData
 */
export interface AdminOrderListData {
    /**
     *
     * @type {Array<AdminOrder>}
     * @memberof AdminOrderListData
     */
    items: Array<AdminOrder>;
    /**
     *
     * @type {string}
     * @memberof AdminOrderListData
     */
    nextCursor: string | null;
    /**
     *
     * @type {boolean}
     * @memberof AdminOrderListData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the AdminOrderListData interface.
 */
export function instanceOfAdminOrderListData(value: object): value is AdminOrderListData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function AdminOrderListDataFromJSON(json: any): AdminOrderListData {
    return AdminOrderListDataFromJSONTyped(json, false);
}

export function AdminOrderListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrderListData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(AdminOrderFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function AdminOrderListDataToJSON(json: any): AdminOrderListData {
    return AdminOrderListDataToJSONTyped(json, false);
}

export function AdminOrderListDataToJSONTyped(value?: AdminOrderListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(AdminOrderToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
