/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminAuthenticationData } from './AdminAuthenticationData';
import {
    AdminAuthenticationDataFromJSON,
    AdminAuthenticationDataFromJSONTyped,
    AdminAuthenticationDataToJSON,
    AdminAuthenticationDataToJSONTyped,
} from './AdminAuthenticationData';

/**
 *
 * @export
 * @interface AdminAuthenticationResponse
 */
export interface AdminAuthenticationResponse {
    /**
     *
     * @type {string}
     * @memberof AdminAuthenticationResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AdminAuthenticationResponse
     */
    message: string;
    /**
     *
     * @type {AdminAuthenticationData}
     * @memberof AdminAuthenticationResponse
     */
    data: AdminAuthenticationData;
    /**
     *
     * @type {string}
     * @memberof AdminAuthenticationResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AdminAuthenticationResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AdminAuthenticationResponse interface.
 */
export function instanceOfAdminAuthenticationResponse(value: object): value is AdminAuthenticationResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AdminAuthenticationResponseFromJSON(json: any): AdminAuthenticationResponse {
    return AdminAuthenticationResponseFromJSONTyped(json, false);
}

export function AdminAuthenticationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuthenticationResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AdminAuthenticationDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AdminAuthenticationResponseToJSON(json: any): AdminAuthenticationResponse {
    return AdminAuthenticationResponseToJSONTyped(json, false);
}

export function AdminAuthenticationResponseToJSONTyped(value?: AdminAuthenticationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AdminAuthenticationDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
