/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AdminSessionSummary
 */
export interface AdminSessionSummary {
    /**
     *
     * @type {string}
     * @memberof AdminSessionSummary
     */
    sessionId: string;
    /**
     *
     * @type {Date}
     * @memberof AdminSessionSummary
     */
    mfaVerifiedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminSessionSummary
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminSessionSummary
     */
    lastSeenAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AdminSessionSummary
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the AdminSessionSummary interface.
 */
export function instanceOfAdminSessionSummary(value: object): value is AdminSessionSummary {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('mfaVerifiedAt' in value) || value['mfaVerifiedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lastSeenAt' in value) || value['lastSeenAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function AdminSessionSummaryFromJSON(json: any): AdminSessionSummary {
    return AdminSessionSummaryFromJSONTyped(json, false);
}

export function AdminSessionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSessionSummary {
    if (json == null) {
        return json;
    }
    return {

        'sessionId': json['sessionId'],
        'mfaVerifiedAt': (new Date(json['mfaVerifiedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'lastSeenAt': (new Date(json['lastSeenAt'])),
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function AdminSessionSummaryToJSON(json: any): AdminSessionSummary {
    return AdminSessionSummaryToJSONTyped(json, false);
}

export function AdminSessionSummaryToJSONTyped(value?: AdminSessionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'sessionId': value['sessionId'],
        'mfaVerifiedAt': value['mfaVerifiedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'lastSeenAt': value['lastSeenAt'].toISOString(),
        'expiresAt': value['expiresAt'].toISOString(),
    };
}
