/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdRewardSession } from './AdRewardSession';
import {
    AdRewardSessionFromJSON,
    AdRewardSessionFromJSONTyped,
    AdRewardSessionToJSON,
    AdRewardSessionToJSONTyped,
} from './AdRewardSession';

/**
 *
 * @export
 * @interface AdRewardSessionResponse
 */
export interface AdRewardSessionResponse {
    /**
     *
     * @type {string}
     * @memberof AdRewardSessionResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AdRewardSessionResponse
     */
    message: string;
    /**
     *
     * @type {AdRewardSession}
     * @memberof AdRewardSessionResponse
     */
    data: AdRewardSession;
    /**
     *
     * @type {string}
     * @memberof AdRewardSessionResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AdRewardSessionResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AdRewardSessionResponse interface.
 */
export function instanceOfAdRewardSessionResponse(value: object): value is AdRewardSessionResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AdRewardSessionResponseFromJSON(json: any): AdRewardSessionResponse {
    return AdRewardSessionResponseFromJSONTyped(json, false);
}

export function AdRewardSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdRewardSessionResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AdRewardSessionFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AdRewardSessionResponseToJSON(json: any): AdRewardSessionResponse {
    return AdRewardSessionResponseToJSONTyped(json, false);
}

export function AdRewardSessionResponseToJSONTyped(value?: AdRewardSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AdRewardSessionToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
