/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiModelMapping } from './AiModelMapping';
import {
    AiModelMappingFromJSON,
    AiModelMappingFromJSONTyped,
    AiModelMappingToJSON,
    AiModelMappingToJSONTyped,
} from './AiModelMapping';

/**
 *
 * @export
 * @interface AiModelMappingResponse
 */
export interface AiModelMappingResponse {
    /**
     *
     * @type {string}
     * @memberof AiModelMappingResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AiModelMappingResponse
     */
    message: string;
    /**
     *
     * @type {AiModelMapping}
     * @memberof AiModelMappingResponse
     */
    data: AiModelMapping;
    /**
     *
     * @type {string}
     * @memberof AiModelMappingResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AiModelMappingResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AiModelMappingResponse interface.
 */
export function instanceOfAiModelMappingResponse(value: object): value is AiModelMappingResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AiModelMappingResponseFromJSON(json: any): AiModelMappingResponse {
    return AiModelMappingResponseFromJSONTyped(json, false);
}

export function AiModelMappingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiModelMappingResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AiModelMappingFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AiModelMappingResponseToJSON(json: any): AiModelMappingResponse {
    return AiModelMappingResponseToJSONTyped(json, false);
}

export function AiModelMappingResponseToJSONTyped(value?: AiModelMappingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AiModelMappingToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
