/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiPromptTemplate } from './AiPromptTemplate';
import {
    AiPromptTemplateFromJSON,
    AiPromptTemplateFromJSONTyped,
    AiPromptTemplateToJSON,
    AiPromptTemplateToJSONTyped,
} from './AiPromptTemplate';

/**
 *
 * @export
 * @interface AiPromptResponse
 */
export interface AiPromptResponse {
    /**
     *
     * @type {string}
     * @memberof AiPromptResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AiPromptResponse
     */
    message: string;
    /**
     *
     * @type {AiPromptTemplate}
     * @memberof AiPromptResponse
     */
    data: AiPromptTemplate;
    /**
     *
     * @type {string}
     * @memberof AiPromptResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AiPromptResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AiPromptResponse interface.
 */
export function instanceOfAiPromptResponse(value: object): value is AiPromptResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AiPromptResponseFromJSON(json: any): AiPromptResponse {
    return AiPromptResponseFromJSONTyped(json, false);
}

export function AiPromptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiPromptResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AiPromptTemplateFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AiPromptResponseToJSON(json: any): AiPromptResponse {
    return AiPromptResponseToJSONTyped(json, false);
}

export function AiPromptResponseToJSONTyped(value?: AiPromptResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AiPromptTemplateToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
