/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiPromptTemplate } from './AiPromptTemplate';
import {
    AiPromptTemplateFromJSON,
    AiPromptTemplateFromJSONTyped,
    AiPromptTemplateToJSON,
    AiPromptTemplateToJSONTyped,
} from './AiPromptTemplate';

/**
 *
 * @export
 * @interface AiPromptListData
 */
export interface AiPromptListData {
    /**
     *
     * @type {Array<AiPromptTemplate>}
     * @memberof AiPromptListData
     */
    items: Array<AiPromptTemplate>;
    /**
     *
     * @type {string}
     * @memberof AiPromptListData
     */
    nextCursor: string | null;
    /**
     *
     * @type {boolean}
     * @memberof AiPromptListData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the AiPromptListData interface.
 */
export function instanceOfAiPromptListData(value: object): value is AiPromptListData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function AiPromptListDataFromJSON(json: any): AiPromptListData {
    return AiPromptListDataFromJSONTyped(json, false);
}

export function AiPromptListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiPromptListData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(AiPromptTemplateFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function AiPromptListDataToJSON(json: any): AiPromptListData {
    return AiPromptListDataToJSONTyped(json, false);
}

export function AiPromptListDataToJSONTyped(value?: AiPromptListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(AiPromptTemplateToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
