/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiResourceStatus } from './AiResourceStatus';
import {
    AiResourceStatusFromJSON,
    AiResourceStatusFromJSONTyped,
    AiResourceStatusToJSON,
    AiResourceStatusToJSONTyped,
} from './AiResourceStatus';
import type { AiScenario } from './AiScenario';
import {
    AiScenarioFromJSON,
    AiScenarioFromJSONTyped,
    AiScenarioToJSON,
    AiScenarioToJSONTyped,
} from './AiScenario';

/**
 *
 * @export
 * @interface AiPromptTemplate
 */
export interface AiPromptTemplate {
    /**
     *
     * @type {string}
     * @memberof AiPromptTemplate
     */
    promptId: string;
    /**
     *
     * @type {number}
     * @memberof AiPromptTemplate
     */
    version: number;
    /**
     *
     * @type {string}
     * @memberof AiPromptTemplate
     */
    promptCode: string;
    /**
     *
     * @type {AiScenario}
     * @memberof AiPromptTemplate
     */
    scenario: AiScenario;
    /**
     *
     * @type {string}
     * @memberof AiPromptTemplate
     */
    systemTemplate: string;
    /**
     *
     * @type {string}
     * @memberof AiPromptTemplate
     */
    userTemplate: string;
    /**
     *
     * @type {Set<string>}
     * @memberof AiPromptTemplate
     */
    allowedInputFields: Set<string>;
    /**
     * Declarative JSON Schema only; executable expressions are forbidden.
     * @type {object}
     * @memberof AiPromptTemplate
     */
    outputSchema: object;
    /**
     *
     * @type {string}
     * @memberof AiPromptTemplate
     */
    safetyPolicyId?: string | null;
    /**
     *
     * @type {AiResourceStatus}
     * @memberof AiPromptTemplate
     */
    status: AiResourceStatus;
    /**
     *
     * @type {Date}
     * @memberof AiPromptTemplate
     */
    effectiveAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof AiPromptTemplate
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof AiPromptTemplate
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof AiPromptTemplate
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the AiPromptTemplate interface.
 */
export function instanceOfAiPromptTemplate(value: object): value is AiPromptTemplate {
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('promptCode' in value) || value['promptCode'] === undefined) return false;
    if (!('scenario' in value) || value['scenario'] === undefined) return false;
    if (!('systemTemplate' in value) || value['systemTemplate'] === undefined) return false;
    if (!('userTemplate' in value) || value['userTemplate'] === undefined) return false;
    if (!('allowedInputFields' in value) || value['allowedInputFields'] === undefined) return false;
    if (!('outputSchema' in value) || value['outputSchema'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AiPromptTemplateFromJSON(json: any): AiPromptTemplate {
    return AiPromptTemplateFromJSONTyped(json, false);
}

export function AiPromptTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiPromptTemplate {
    if (json == null) {
        return json;
    }
    return {

        'promptId': json['promptId'],
        'version': json['version'],
        'promptCode': json['promptCode'],
        'scenario': AiScenarioFromJSON(json['scenario']),
        'systemTemplate': json['systemTemplate'],
        'userTemplate': json['userTemplate'],
        'allowedInputFields': new Set(json['allowedInputFields']),
        'outputSchema': json['outputSchema'],
        'safetyPolicyId': json['safetyPolicyId'] === undefined ? undefined : json['safetyPolicyId'] === null ? null : json['safetyPolicyId'],
        'status': AiResourceStatusFromJSON(json['status']),
        'effectiveAt': json['effectiveAt'] === undefined ? undefined : json['effectiveAt'] === null ? null : (new Date(json['effectiveAt'])),
        'resourceVersion': json['resourceVersion'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function AiPromptTemplateToJSON(json: any): AiPromptTemplate {
    return AiPromptTemplateToJSONTyped(json, false);
}

export function AiPromptTemplateToJSONTyped(value?: AiPromptTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'promptId': value['promptId'],
        'version': value['version'],
        'promptCode': value['promptCode'],
        'scenario': AiScenarioToJSON(value['scenario']),
        'systemTemplate': value['systemTemplate'],
        'userTemplate': value['userTemplate'],
        'allowedInputFields': Array.from(value['allowedInputFields'] as Set<any>),
        'outputSchema': value['outputSchema'],
        'safetyPolicyId': value['safetyPolicyId'],
        'status': AiResourceStatusToJSON(value['status']),
        'effectiveAt': value['effectiveAt'] == null ? value['effectiveAt'] : value['effectiveAt'].toISOString(),
        'resourceVersion': value['resourceVersion'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
