/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiRiskPolicy } from './AiRiskPolicy';
import {
    AiRiskPolicyFromJSON,
    AiRiskPolicyFromJSONTyped,
    AiRiskPolicyToJSON,
    AiRiskPolicyToJSONTyped,
} from './AiRiskPolicy';

/**
 *
 * @export
 * @interface AiRiskPolicyListData
 */
export interface AiRiskPolicyListData {
    /**
     *
     * @type {Array<AiRiskPolicy>}
     * @memberof AiRiskPolicyListData
     */
    items: Array<AiRiskPolicy>;
    /**
     *
     * @type {string}
     * @memberof AiRiskPolicyListData
     */
    nextCursor: string | null;
    /**
     *
     * @type {boolean}
     * @memberof AiRiskPolicyListData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the AiRiskPolicyListData interface.
 */
export function instanceOfAiRiskPolicyListData(value: object): value is AiRiskPolicyListData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function AiRiskPolicyListDataFromJSON(json: any): AiRiskPolicyListData {
    return AiRiskPolicyListDataFromJSONTyped(json, false);
}

export function AiRiskPolicyListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiRiskPolicyListData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(AiRiskPolicyFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function AiRiskPolicyListDataToJSON(json: any): AiRiskPolicyListData {
    return AiRiskPolicyListDataToJSONTyped(json, false);
}

export function AiRiskPolicyListDataToJSONTyped(value?: AiRiskPolicyListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(AiRiskPolicyToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
