/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiRiskPolicy } from './AiRiskPolicy';
import {
    AiRiskPolicyFromJSON,
    AiRiskPolicyFromJSONTyped,
    AiRiskPolicyToJSON,
    AiRiskPolicyToJSONTyped,
} from './AiRiskPolicy';

/**
 *
 * @export
 * @interface AiRiskPolicyResponse
 */
export interface AiRiskPolicyResponse {
    /**
     *
     * @type {string}
     * @memberof AiRiskPolicyResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AiRiskPolicyResponse
     */
    message: string;
    /**
     *
     * @type {AiRiskPolicy}
     * @memberof AiRiskPolicyResponse
     */
    data: AiRiskPolicy;
    /**
     *
     * @type {string}
     * @memberof AiRiskPolicyResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AiRiskPolicyResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AiRiskPolicyResponse interface.
 */
export function instanceOfAiRiskPolicyResponse(value: object): value is AiRiskPolicyResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AiRiskPolicyResponseFromJSON(json: any): AiRiskPolicyResponse {
    return AiRiskPolicyResponseFromJSONTyped(json, false);
}

export function AiRiskPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiRiskPolicyResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AiRiskPolicyFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AiRiskPolicyResponseToJSON(json: any): AiRiskPolicyResponse {
    return AiRiskPolicyResponseToJSONTyped(json, false);
}

export function AiRiskPolicyResponseToJSONTyped(value?: AiRiskPolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AiRiskPolicyToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
