/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuditReasonRequest
 */
export interface AuditReasonRequest {
    /**
     *
     * @type {string}
     * @memberof AuditReasonRequest
     */
    auditReason: string;
}

/**
 * Check if a given object implements the AuditReasonRequest interface.
 */
export function instanceOfAuditReasonRequest(value: object): value is AuditReasonRequest {
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    return true;
}

export function AuditReasonRequestFromJSON(json: any): AuditReasonRequest {
    return AuditReasonRequestFromJSONTyped(json, false);
}

export function AuditReasonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditReasonRequest {
    if (json == null) {
        return json;
    }
    return {

        'auditReason': json['auditReason'],
    };
}

export function AuditReasonRequestToJSON(json: any): AuditReasonRequest {
    return AuditReasonRequestToJSONTyped(json, false);
}

export function AuditReasonRequestToJSONTyped(value?: AuditReasonRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'auditReason': value['auditReason'],
    };
}
