/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditExportContentData } from './AuditExportContentData';
import {
    AuditExportContentDataFromJSON,
    AuditExportContentDataFromJSONTyped,
    AuditExportContentDataToJSON,
    AuditExportContentDataToJSONTyped,
} from './AuditExportContentData';

/**
 *
 * @export
 * @interface AuditExportContentResponse
 */
export interface AuditExportContentResponse {
    /**
     *
     * @type {string}
     * @memberof AuditExportContentResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AuditExportContentResponse
     */
    message: string;
    /**
     *
     * @type {AuditExportContentData}
     * @memberof AuditExportContentResponse
     */
    data: AuditExportContentData;
    /**
     *
     * @type {string}
     * @memberof AuditExportContentResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AuditExportContentResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AuditExportContentResponse interface.
 */
export function instanceOfAuditExportContentResponse(value: object): value is AuditExportContentResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AuditExportContentResponseFromJSON(json: any): AuditExportContentResponse {
    return AuditExportContentResponseFromJSONTyped(json, false);
}

export function AuditExportContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditExportContentResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AuditExportContentDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AuditExportContentResponseToJSON(json: any): AuditExportContentResponse {
    return AuditExportContentResponseToJSONTyped(json, false);
}

export function AuditExportContentResponseToJSONTyped(value?: AuditExportContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AuditExportContentDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
