/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEvent } from './AuditEvent';
import {
    AuditEventFromJSON,
    AuditEventFromJSONTyped,
    AuditEventToJSON,
    AuditEventToJSONTyped,
} from './AuditEvent';

/**
 *
 * @export
 * @interface AuditEventListData
 */
export interface AuditEventListData {
    /**
     *
     * @type {Array<AuditEvent>}
     * @memberof AuditEventListData
     */
    items: Array<AuditEvent>;
    /**
     *
     * @type {string}
     * @memberof AuditEventListData
     */
    nextCursor?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof AuditEventListData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the AuditEventListData interface.
 */
export function instanceOfAuditEventListData(value: object): value is AuditEventListData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function AuditEventListDataFromJSON(json: any): AuditEventListData {
    return AuditEventListDataFromJSONTyped(json, false);
}

export function AuditEventListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEventListData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(AuditEventFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function AuditEventListDataToJSON(json: any): AuditEventListData {
    return AuditEventListDataToJSONTyped(json, false);
}

export function AuditEventListDataToJSONTyped(value?: AuditEventListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(AuditEventToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
