/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEvent } from './AuditEvent';
import {
    AuditEventFromJSON,
    AuditEventFromJSONTyped,
    AuditEventToJSON,
    AuditEventToJSONTyped,
} from './AuditEvent';

/**
 *
 * @export
 * @interface AuditEventResponse
 */
export interface AuditEventResponse {
    /**
     *
     * @type {string}
     * @memberof AuditEventResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof AuditEventResponse
     */
    message: string;
    /**
     *
     * @type {AuditEvent}
     * @memberof AuditEventResponse
     */
    data: AuditEvent;
    /**
     *
     * @type {string}
     * @memberof AuditEventResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof AuditEventResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the AuditEventResponse interface.
 */
export function instanceOfAuditEventResponse(value: object): value is AuditEventResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AuditEventResponseFromJSON(json: any): AuditEventResponse {
    return AuditEventResponseFromJSONTyped(json, false);
}

export function AuditEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEventResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': AuditEventFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function AuditEventResponseToJSON(json: any): AuditEventResponse {
    return AuditEventResponseToJSONTyped(json, false);
}

export function AuditEventResponseToJSONTyped(value?: AuditEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': AuditEventToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
