/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const AuthChallengeMode = {
    Otp: 'OTP'
} as const;
export type AuthChallengeMode = typeof AuthChallengeMode[keyof typeof AuthChallengeMode];


export function instanceOfAuthChallengeMode(value: any): boolean {
    for (const key in AuthChallengeMode) {
        if (Object.prototype.hasOwnProperty.call(AuthChallengeMode, key)) {
            if (AuthChallengeMode[key as keyof typeof AuthChallengeMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuthChallengeModeFromJSON(json: any): AuthChallengeMode {
    return AuthChallengeModeFromJSONTyped(json, false);
}

export function AuthChallengeModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthChallengeMode {
    return json as AuthChallengeMode;
}

export function AuthChallengeModeToJSON(value?: AuthChallengeMode | null): any {
    return value as any;
}

export function AuthChallengeModeToJSONTyped(value: any, ignoreDiscriminator: boolean): AuthChallengeMode {
    return value as AuthChallengeMode;
}
