/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BenefitGrant
 */
export interface BenefitGrant {
    /**
     *
     * @type {number}
     * @memberof BenefitGrant
     */
    textQuota: number;
    /**
     *
     * @type {number}
     * @memberof BenefitGrant
     */
    visionQuota: number;
    /**
     *
     * @type {number}
     * @memberof BenefitGrant
     */
    energyAmount: number;
    /**
     *
     * @type {Set<string>}
     * @memberof BenefitGrant
     */
    allowedModelIds: Set<string>;
    /**
     *
     * @type {Set<string>}
     * @memberof BenefitGrant
     */
    allowedStyleIds: Set<string>;
    /**
     *
     * @type {boolean}
     * @memberof BenefitGrant
     */
    deepAnalysisEnabled?: boolean;
}

/**
 * Check if a given object implements the BenefitGrant interface.
 */
export function instanceOfBenefitGrant(value: object): value is BenefitGrant {
    if (!('textQuota' in value) || value['textQuota'] === undefined) return false;
    if (!('visionQuota' in value) || value['visionQuota'] === undefined) return false;
    if (!('energyAmount' in value) || value['energyAmount'] === undefined) return false;
    if (!('allowedModelIds' in value) || value['allowedModelIds'] === undefined) return false;
    if (!('allowedStyleIds' in value) || value['allowedStyleIds'] === undefined) return false;
    return true;
}

export function BenefitGrantFromJSON(json: any): BenefitGrant {
    return BenefitGrantFromJSONTyped(json, false);
}

export function BenefitGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): BenefitGrant {
    if (json == null) {
        return json;
    }
    return {

        'textQuota': json['textQuota'],
        'visionQuota': json['visionQuota'],
        'energyAmount': json['energyAmount'],
        'allowedModelIds': new Set(json['allowedModelIds']),
        'allowedStyleIds': new Set(json['allowedStyleIds']),
        'deepAnalysisEnabled': json['deepAnalysisEnabled'] == null ? undefined : json['deepAnalysisEnabled'],
    };
}

export function BenefitGrantToJSON(json: any): BenefitGrant {
    return BenefitGrantToJSONTyped(json, false);
}

export function BenefitGrantToJSONTyped(value?: BenefitGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'textQuota': value['textQuota'],
        'visionQuota': value['visionQuota'],
        'energyAmount': value['energyAmount'],
        'allowedModelIds': Array.from(value['allowedModelIds'] as Set<any>),
        'allowedStyleIds': Array.from(value['allowedStyleIds'] as Set<any>),
        'deepAnalysisEnabled': value['deepAnalysisEnabled'],
    };
}
