/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const CandidateActionType = {
    Copy: 'COPY',
    Favorite: 'FAVORITE',
    Sent: 'SENT',
    Like: 'LIKE',
    Dislike: 'DISLIKE',
    Outcome: 'OUTCOME'
} as const;
export type CandidateActionType = typeof CandidateActionType[keyof typeof CandidateActionType];


export function instanceOfCandidateActionType(value: any): boolean {
    for (const key in CandidateActionType) {
        if (Object.prototype.hasOwnProperty.call(CandidateActionType, key)) {
            if (CandidateActionType[key as keyof typeof CandidateActionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CandidateActionTypeFromJSON(json: any): CandidateActionType {
    return CandidateActionTypeFromJSONTyped(json, false);
}

export function CandidateActionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandidateActionType {
    return json as CandidateActionType;
}

export function CandidateActionTypeToJSON(value?: CandidateActionType | null): any {
    return value as any;
}

export function CandidateActionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CandidateActionType {
    return value as CandidateActionType;
}
