/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CandidateActionType } from './CandidateActionType';
import {
    CandidateActionTypeFromJSON,
    CandidateActionTypeFromJSONTyped,
    CandidateActionTypeToJSON,
    CandidateActionTypeToJSONTyped,
} from './CandidateActionType';

/**
 *
 * @export
 * @interface CandidateActionRequest
 */
export interface CandidateActionRequest {
    /**
     *
     * @type {string}
     * @memberof CandidateActionRequest
     */
    clientActionId: string;
    /**
     *
     * @type {CandidateActionType}
     * @memberof CandidateActionRequest
     */
    actionType: CandidateActionType;
    /**
     *
     * @type {Date}
     * @memberof CandidateActionRequest
     */
    occurredAt: Date;
    /**
     *
     * @type {CandidateActionRequestOutcomeCodeEnum}
     * @memberof CandidateActionRequest
     */
    outcomeCode?: CandidateActionRequestOutcomeCodeEnum | null;
}


/**
 * @export
 */
export const CandidateActionRequestOutcomeCodeEnum = {
    Positive: 'POSITIVE',
    Neutral: 'NEUTRAL',
    Negative: 'NEGATIVE',
    Unknown: 'UNKNOWN'
} as const;
export type CandidateActionRequestOutcomeCodeEnum = typeof CandidateActionRequestOutcomeCodeEnum[keyof typeof CandidateActionRequestOutcomeCodeEnum];


/**
 * Check if a given object implements the CandidateActionRequest interface.
 */
export function instanceOfCandidateActionRequest(value: object): value is CandidateActionRequest {
    if (!('clientActionId' in value) || value['clientActionId'] === undefined) return false;
    if (!('actionType' in value) || value['actionType'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    return true;
}

export function CandidateActionRequestFromJSON(json: any): CandidateActionRequest {
    return CandidateActionRequestFromJSONTyped(json, false);
}

export function CandidateActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandidateActionRequest {
    if (json == null) {
        return json;
    }
    return {

        'clientActionId': json['clientActionId'],
        'actionType': CandidateActionTypeFromJSON(json['actionType']),
        'occurredAt': (new Date(json['occurredAt'])),
        'outcomeCode': json['outcomeCode'] === undefined ? undefined : json['outcomeCode'] === null ? null : json['outcomeCode'],
    };
}

export function CandidateActionRequestToJSON(json: any): CandidateActionRequest {
    return CandidateActionRequestToJSONTyped(json, false);
}

export function CandidateActionRequestToJSONTyped(value?: CandidateActionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'clientActionId': value['clientActionId'],
        'actionType': CandidateActionTypeToJSON(value['actionType']),
        'occurredAt': value['occurredAt'].toISOString(),
        'outcomeCode': value['outcomeCode'],
    };
}
