/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsentType } from './ConsentType';
import {
    ConsentTypeFromJSON,
    ConsentTypeFromJSONTyped,
    ConsentTypeToJSON,
    ConsentTypeToJSONTyped,
} from './ConsentType';

/**
 *
 * @export
 * @interface ConsentRecord
 */
export interface ConsentRecord {
    /**
     *
     * @type {ConsentType}
     * @memberof ConsentRecord
     */
    consentType: ConsentType;
    /**
     *
     * @type {string}
     * @memberof ConsentRecord
     */
    documentVersion: string;
    /**
     *
     * @type {boolean}
     * @memberof ConsentRecord
     */
    granted: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ConsentRecord
     */
    required: boolean;
    /**
     *
     * @type {Date}
     * @memberof ConsentRecord
     */
    grantedAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof ConsentRecord
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof ConsentRecord
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ConsentRecord interface.
 */
export function instanceOfConsentRecord(value: object): value is ConsentRecord {
    if (!('consentType' in value) || value['consentType'] === undefined) return false;
    if (!('documentVersion' in value) || value['documentVersion'] === undefined) return false;
    if (!('granted' in value) || value['granted'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ConsentRecordFromJSON(json: any): ConsentRecord {
    return ConsentRecordFromJSONTyped(json, false);
}

export function ConsentRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentRecord {
    if (json == null) {
        return json;
    }
    return {

        'consentType': ConsentTypeFromJSON(json['consentType']),
        'documentVersion': json['documentVersion'],
        'granted': json['granted'],
        'required': json['required'],
        'grantedAt': json['grantedAt'] === undefined ? undefined : json['grantedAt'] === null ? null : (new Date(json['grantedAt'])),
        'resourceVersion': json['resourceVersion'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ConsentRecordToJSON(json: any): ConsentRecord {
    return ConsentRecordToJSONTyped(json, false);
}

export function ConsentRecordToJSONTyped(value?: ConsentRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'consentType': ConsentTypeToJSON(value['consentType']),
        'documentVersion': value['documentVersion'],
        'granted': value['granted'],
        'required': value['required'],
        'grantedAt': value['grantedAt'] == null ? value['grantedAt'] : value['grantedAt'].toISOString(),
        'resourceVersion': value['resourceVersion'],
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
