/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const ConsentType = {
    TermsOfService: 'TERMS_OF_SERVICE',
    PrivacyPolicy: 'PRIVACY_POLICY',
    ServiceRequired: 'SERVICE_REQUIRED',
    ModelTraining: 'MODEL_TRAINING',
    Marketing: 'MARKETING'
} as const;
export type ConsentType = typeof ConsentType[keyof typeof ConsentType];


export function instanceOfConsentType(value: any): boolean {
    for (const key in ConsentType) {
        if (Object.prototype.hasOwnProperty.call(ConsentType, key)) {
            if (ConsentType[key as keyof typeof ConsentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConsentTypeFromJSON(json: any): ConsentType {
    return ConsentTypeFromJSONTyped(json, false);
}

export function ConsentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentType {
    return json as ConsentType;
}

export function ConsentTypeToJSON(value?: ConsentType | null): any {
    return value as any;
}

export function ConsentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ConsentType {
    return value as ConsentType;
}
