/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsentRecord } from './ConsentRecord';
import {
    ConsentRecordFromJSON,
    ConsentRecordFromJSONTyped,
    ConsentRecordToJSON,
    ConsentRecordToJSONTyped,
} from './ConsentRecord';

/**
 *
 * @export
 * @interface ConsentResponse
 */
export interface ConsentResponse {
    /**
     *
     * @type {string}
     * @memberof ConsentResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ConsentResponse
     */
    message: string;
    /**
     *
     * @type {ConsentRecord}
     * @memberof ConsentResponse
     */
    data: ConsentRecord;
    /**
     *
     * @type {string}
     * @memberof ConsentResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof ConsentResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ConsentResponse interface.
 */
export function instanceOfConsentResponse(value: object): value is ConsentResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ConsentResponseFromJSON(json: any): ConsentResponse {
    return ConsentResponseFromJSONTyped(json, false);
}

export function ConsentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': ConsentRecordFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ConsentResponseToJSON(json: any): ConsentResponse {
    return ConsentResponseToJSONTyped(json, false);
}

export function ConsentResponseToJSONTyped(value?: ConsentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': ConsentRecordToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
