/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsentListData } from './ConsentListData';
import {
    ConsentListDataFromJSON,
    ConsentListDataFromJSONTyped,
    ConsentListDataToJSON,
    ConsentListDataToJSONTyped,
} from './ConsentListData';

/**
 *
 * @export
 * @interface ConsentListResponse
 */
export interface ConsentListResponse {
    /**
     *
     * @type {string}
     * @memberof ConsentListResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ConsentListResponse
     */
    message: string;
    /**
     *
     * @type {ConsentListData}
     * @memberof ConsentListResponse
     */
    data: ConsentListData;
    /**
     *
     * @type {string}
     * @memberof ConsentListResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof ConsentListResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ConsentListResponse interface.
 */
export function instanceOfConsentListResponse(value: object): value is ConsentListResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ConsentListResponseFromJSON(json: any): ConsentListResponse {
    return ConsentListResponseFromJSONTyped(json, false);
}

export function ConsentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsentListResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': ConsentListDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ConsentListResponseToJSON(json: any): ConsentListResponse {
    return ConsentListResponseToJSONTyped(json, false);
}

export function ConsentListResponseToJSONTyped(value?: ConsentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': ConsentListDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
