/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateSupportTicketRequest
 */
export interface CreateSupportTicketRequest {
    /**
     *
     * @type {CreateSupportTicketRequestCategoryEnum}
     * @memberof CreateSupportTicketRequest
     */
    category: CreateSupportTicketRequestCategoryEnum;
    /**
     *
     * @type {string}
     * @memberof CreateSupportTicketRequest
     */
    subject: string;
    /**
     *
     * @type {string}
     * @memberof CreateSupportTicketRequest
     */
    body: string;
}


/**
 * @export
 */
export const CreateSupportTicketRequestCategoryEnum = {
    General: 'GENERAL',
    Account: 'ACCOUNT',
    Payment: 'PAYMENT',
    Privacy: 'PRIVACY',
    Complaint: 'COMPLAINT'
} as const;
export type CreateSupportTicketRequestCategoryEnum = typeof CreateSupportTicketRequestCategoryEnum[keyof typeof CreateSupportTicketRequestCategoryEnum];


/**
 * Check if a given object implements the CreateSupportTicketRequest interface.
 */
export function instanceOfCreateSupportTicketRequest(value: object): value is CreateSupportTicketRequest {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CreateSupportTicketRequestFromJSON(json: any): CreateSupportTicketRequest {
    return CreateSupportTicketRequestFromJSONTyped(json, false);
}

export function CreateSupportTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSupportTicketRequest {
    if (json == null) {
        return json;
    }
    return {

        'category': json['category'],
        'subject': json['subject'],
        'body': json['body'],
    };
}

export function CreateSupportTicketRequestToJSON(json: any): CreateSupportTicketRequest {
    return CreateSupportTicketRequestToJSONTyped(json, false);
}

export function CreateSupportTicketRequestToJSONTyped(value?: CreateSupportTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'category': value['category'],
        'subject': value['subject'],
        'body': value['body'],
    };
}
