/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';

/**
 *
 * @export
 * @interface CreatePaymentAttemptRequest
 */
export interface CreatePaymentAttemptRequest {
    /**
     *
     * @type {PaymentMethod}
     * @memberof CreatePaymentAttemptRequest
     */
    paymentMethod: PaymentMethod;
}



/**
 * Check if a given object implements the CreatePaymentAttemptRequest interface.
 */
export function instanceOfCreatePaymentAttemptRequest(value: object): value is CreatePaymentAttemptRequest {
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function CreatePaymentAttemptRequestFromJSON(json: any): CreatePaymentAttemptRequest {
    return CreatePaymentAttemptRequestFromJSONTyped(json, false);
}

export function CreatePaymentAttemptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentAttemptRequest {
    if (json == null) {
        return json;
    }
    return {

        'paymentMethod': PaymentMethodFromJSON(json['paymentMethod']),
    };
}

export function CreatePaymentAttemptRequestToJSON(json: any): CreatePaymentAttemptRequest {
    return CreatePaymentAttemptRequestToJSONTyped(json, false);
}

export function CreatePaymentAttemptRequestToJSONTyped(value?: CreatePaymentAttemptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'paymentMethod': PaymentMethodToJSON(value['paymentMethod']),
    };
}
