/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialRotation } from './CredentialRotation';
import {
    CredentialRotationFromJSON,
    CredentialRotationFromJSONTyped,
    CredentialRotationToJSON,
    CredentialRotationToJSONTyped,
} from './CredentialRotation';

/**
 *
 * @export
 * @interface CredentialRotationResponse
 */
export interface CredentialRotationResponse {
    /**
     *
     * @type {string}
     * @memberof CredentialRotationResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof CredentialRotationResponse
     */
    message: string;
    /**
     *
     * @type {CredentialRotation}
     * @memberof CredentialRotationResponse
     */
    data: CredentialRotation;
    /**
     *
     * @type {string}
     * @memberof CredentialRotationResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof CredentialRotationResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the CredentialRotationResponse interface.
 */
export function instanceOfCredentialRotationResponse(value: object): value is CredentialRotationResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CredentialRotationResponseFromJSON(json: any): CredentialRotationResponse {
    return CredentialRotationResponseFromJSONTyped(json, false);
}

export function CredentialRotationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialRotationResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': CredentialRotationFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function CredentialRotationResponseToJSON(json: any): CredentialRotationResponse {
    return CredentialRotationResponseToJSONTyped(json, false);
}

export function CredentialRotationResponseToJSONTyped(value?: CredentialRotationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': CredentialRotationToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
