/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CredentialRotation
 */
export interface CredentialRotation {
    /**
     *
     * @type {string}
     * @memberof CredentialRotation
     */
    credentialVersionId: string;
    /**
     *
     * @type {string}
     * @memberof CredentialRotation
     */
    fingerprint: string;
    /**
     *
     * @type {Date}
     * @memberof CredentialRotation
     */
    rotatedAt: Date;
    /**
     *
     * @type {number}
     * @memberof CredentialRotation
     */
    resourceVersion: number;
}

/**
 * Check if a given object implements the CredentialRotation interface.
 */
export function instanceOfCredentialRotation(value: object): value is CredentialRotation {
    if (!('credentialVersionId' in value) || value['credentialVersionId'] === undefined) return false;
    if (!('fingerprint' in value) || value['fingerprint'] === undefined) return false;
    if (!('rotatedAt' in value) || value['rotatedAt'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    return true;
}

export function CredentialRotationFromJSON(json: any): CredentialRotation {
    return CredentialRotationFromJSONTyped(json, false);
}

export function CredentialRotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialRotation {
    if (json == null) {
        return json;
    }
    return {

        'credentialVersionId': json['credentialVersionId'],
        'fingerprint': json['fingerprint'],
        'rotatedAt': (new Date(json['rotatedAt'])),
        'resourceVersion': json['resourceVersion'],
    };
}

export function CredentialRotationToJSON(json: any): CredentialRotation {
    return CredentialRotationToJSONTyped(json, false);
}

export function CredentialRotationToJSONTyped(value?: CredentialRotation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'credentialVersionId': value['credentialVersionId'],
        'fingerprint': value['fingerprint'],
        'rotatedAt': value['rotatedAt'].toISOString(),
        'resourceVersion': value['resourceVersion'],
    };
}
