/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataRequestBase } from './DataRequestBase';
import {
    DataRequestBaseFromJSON,
    DataRequestBaseFromJSONTyped,
    DataRequestBaseToJSON,
    DataRequestBaseToJSONTyped,
} from './DataRequestBase';

/**
 *
 * @export
 * @interface DataRequestResponse
 */
export interface DataRequestResponse {
    /**
     *
     * @type {string}
     * @memberof DataRequestResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof DataRequestResponse
     */
    message: string;
    /**
     *
     * @type {DataRequestBase}
     * @memberof DataRequestResponse
     */
    data: DataRequestBase;
    /**
     *
     * @type {string}
     * @memberof DataRequestResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof DataRequestResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the DataRequestResponse interface.
 */
export function instanceOfDataRequestResponse(value: object): value is DataRequestResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function DataRequestResponseFromJSON(json: any): DataRequestResponse {
    return DataRequestResponseFromJSONTyped(json, false);
}

export function DataRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataRequestResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': DataRequestBaseFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function DataRequestResponseToJSON(json: any): DataRequestResponse {
    return DataRequestResponseToJSONTyped(json, false);
}

export function DataRequestResponseToJSONTyped(value?: DataRequestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': DataRequestBaseToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
