/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataRequestType } from './DataRequestType';
import {
    DataRequestTypeFromJSON,
    DataRequestTypeFromJSONTyped,
    DataRequestTypeToJSON,
    DataRequestTypeToJSONTyped,
} from './DataRequestType';
import type { DataRequestStatus } from './DataRequestStatus';
import {
    DataRequestStatusFromJSON,
    DataRequestStatusFromJSONTyped,
    DataRequestStatusToJSON,
    DataRequestStatusToJSONTyped,
} from './DataRequestStatus';

/**
 *
 * @export
 * @interface DataRequestBase
 */
export interface DataRequestBase {
    /**
     *
     * @type {string}
     * @memberof DataRequestBase
     */
    requestId: string;
    /**
     *
     * @type {string}
     * @memberof DataRequestBase
     */
    jobId?: string | null;
    /**
     *
     * @type {DataRequestType}
     * @memberof DataRequestBase
     */
    requestType: DataRequestType;
    /**
     *
     * @type {DataRequestStatus}
     * @memberof DataRequestBase
     */
    status: DataRequestStatus;
    /**
     *
     * @type {string}
     * @memberof DataRequestBase
     */
    downloadUrl?: string | null;
    /**
     *
     * @type {Date}
     * @memberof DataRequestBase
     */
    expiresAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof DataRequestBase
     */
    rejectionReasonCode?: string | null;
    /**
     *
     * @type {Date}
     * @memberof DataRequestBase
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof DataRequestBase
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the DataRequestBase interface.
 */
export function instanceOfDataRequestBase(value: object): value is DataRequestBase {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('requestType' in value) || value['requestType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function DataRequestBaseFromJSON(json: any): DataRequestBase {
    return DataRequestBaseFromJSONTyped(json, false);
}

export function DataRequestBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataRequestBase {
    if (json == null) {
        return json;
    }
    return {

        'requestId': json['requestId'],
        'jobId': json['jobId'] === undefined ? undefined : json['jobId'] === null ? null : json['jobId'],
        'requestType': DataRequestTypeFromJSON(json['requestType']),
        'status': DataRequestStatusFromJSON(json['status']),
        'downloadUrl': json['downloadUrl'] === undefined ? undefined : json['downloadUrl'] === null ? null : json['downloadUrl'],
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : (new Date(json['expiresAt'])),
        'rejectionReasonCode': json['rejectionReasonCode'] === undefined ? undefined : json['rejectionReasonCode'] === null ? null : json['rejectionReasonCode'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function DataRequestBaseToJSON(json: any): DataRequestBase {
    return DataRequestBaseToJSONTyped(json, false);
}

export function DataRequestBaseToJSONTyped(value?: DataRequestBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'requestId': value['requestId'],
        'jobId': value['jobId'],
        'requestType': DataRequestTypeToJSON(value['requestType']),
        'status': DataRequestStatusToJSON(value['status']),
        'downloadUrl': value['downloadUrl'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'rejectionReasonCode': value['rejectionReasonCode'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
