/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const DataRequestStatus = {
    Requested: 'REQUESTED',
    IdentityVerified: 'IDENTITY_VERIFIED',
    Processing: 'PROCESSING',
    Completed: 'COMPLETED',
    Rejected: 'REJECTED',
    Cancelled: 'CANCELLED'
} as const;
export type DataRequestStatus = typeof DataRequestStatus[keyof typeof DataRequestStatus];


export function instanceOfDataRequestStatus(value: any): boolean {
    for (const key in DataRequestStatus) {
        if (Object.prototype.hasOwnProperty.call(DataRequestStatus, key)) {
            if (DataRequestStatus[key as keyof typeof DataRequestStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataRequestStatusFromJSON(json: any): DataRequestStatus {
    return DataRequestStatusFromJSONTyped(json, false);
}

export function DataRequestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataRequestStatus {
    return json as DataRequestStatus;
}

export function DataRequestStatusToJSON(value?: DataRequestStatus | null): any {
    return value as any;
}

export function DataRequestStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DataRequestStatus {
    return value as DataRequestStatus;
}
