/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataRequestType } from './DataRequestType';
import {
    DataRequestTypeFromJSON,
    DataRequestTypeFromJSONTyped,
    DataRequestTypeToJSON,
    DataRequestTypeToJSONTyped,
} from './DataRequestType';
import type { DataRequestStatus } from './DataRequestStatus';
import {
    DataRequestStatusFromJSON,
    DataRequestStatusFromJSONTyped,
    DataRequestStatusToJSON,
    DataRequestStatusToJSONTyped,
} from './DataRequestStatus';

/**
 *
 * @export
 * @interface DeletionStatus
 */
export interface DeletionStatus {
    /**
     *
     * @type {string}
     * @memberof DeletionStatus
     */
    requestId: string;
    /**
     *
     * @type {string}
     * @memberof DeletionStatus
     */
    jobId?: string;
    /**
     *
     * @type {DataRequestType}
     * @memberof DeletionStatus
     */
    requestType: DataRequestType;
    /**
     *
     * @type {DataRequestStatus}
     * @memberof DeletionStatus
     */
    status: DataRequestStatus;
    /**
     *
     * @type {string}
     * @memberof DeletionStatus
     */
    downloadUrl?: string;
    /**
     *
     * @type {Date}
     * @memberof DeletionStatus
     */
    expiresAt?: Date;
    /**
     *
     * @type {string}
     * @memberof DeletionStatus
     */
    rejectionReasonCode?: string;
    /**
     *
     * @type {Date}
     * @memberof DeletionStatus
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof DeletionStatus
     */
    updatedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof DeletionStatus
     */
    coolingOffEndsAt: Date;
    /**
     *
     * @type {Date}
     * @memberof DeletionStatus
     */
    estimatedCompletionAt?: Date | null;
    /**
     *
     * @type {Array<string>}
     * @memberof DeletionStatus
     */
    blockers: Array<string>;
}



/**
 * Check if a given object implements the DeletionStatus interface.
 */
export function instanceOfDeletionStatus(value: object): value is DeletionStatus {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('requestType' in value) || value['requestType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('coolingOffEndsAt' in value) || value['coolingOffEndsAt'] === undefined) return false;
    if (!('blockers' in value) || value['blockers'] === undefined) return false;
    return true;
}

export function DeletionStatusFromJSON(json: any): DeletionStatus {
    return DeletionStatusFromJSONTyped(json, false);
}

export function DeletionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletionStatus {
    if (json == null) {
        return json;
    }
    return {

        'requestId': json['requestId'],
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'requestType': DataRequestTypeFromJSON(json['requestType']),
        'status': DataRequestStatusFromJSON(json['status']),
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'rejectionReasonCode': json['rejectionReasonCode'] == null ? undefined : json['rejectionReasonCode'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'coolingOffEndsAt': (new Date(json['coolingOffEndsAt'])),
        'estimatedCompletionAt': json['estimatedCompletionAt'] === undefined ? undefined : json['estimatedCompletionAt'] === null ? null : (new Date(json['estimatedCompletionAt'])),
        'blockers': json['blockers'],
    };
}

export function DeletionStatusToJSON(json: any): DeletionStatus {
    return DeletionStatusToJSONTyped(json, false);
}

export function DeletionStatusToJSONTyped(value?: DeletionStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'requestId': value['requestId'],
        'jobId': value['jobId'],
        'requestType': DataRequestTypeToJSON(value['requestType']),
        'status': DataRequestStatusToJSON(value['status']),
        'downloadUrl': value['downloadUrl'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'rejectionReasonCode': value['rejectionReasonCode'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'coolingOffEndsAt': value['coolingOffEndsAt'].toISOString(),
        'estimatedCompletionAt': value['estimatedCompletionAt'] == null ? value['estimatedCompletionAt'] : value['estimatedCompletionAt'].toISOString(),
        'blockers': value['blockers'],
    };
}
