/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeletionStatus } from './DeletionStatus';
import {
    DeletionStatusFromJSON,
    DeletionStatusFromJSONTyped,
    DeletionStatusToJSON,
    DeletionStatusToJSONTyped,
} from './DeletionStatus';

/**
 *
 * @export
 * @interface DeletionStatusResponse
 */
export interface DeletionStatusResponse {
    /**
     *
     * @type {string}
     * @memberof DeletionStatusResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof DeletionStatusResponse
     */
    message: string;
    /**
     *
     * @type {DeletionStatus}
     * @memberof DeletionStatusResponse
     */
    data: DeletionStatus;
    /**
     *
     * @type {string}
     * @memberof DeletionStatusResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof DeletionStatusResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the DeletionStatusResponse interface.
 */
export function instanceOfDeletionStatusResponse(value: object): value is DeletionStatusResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function DeletionStatusResponseFromJSON(json: any): DeletionStatusResponse {
    return DeletionStatusResponseFromJSONTyped(json, false);
}

export function DeletionStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletionStatusResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': DeletionStatusFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function DeletionStatusResponseToJSON(json: any): DeletionStatusResponse {
    return DeletionStatusResponseToJSONTyped(json, false);
}

export function DeletionStatusResponseToJSONTyped(value?: DeletionStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': DeletionStatusToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
