/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailPurpose } from './EmailPurpose';
import {
    EmailPurposeFromJSON,
    EmailPurposeFromJSONTyped,
    EmailPurposeToJSON,
    EmailPurposeToJSONTyped,
} from './EmailPurpose';

/**
 *
 * @export
 * @interface EmailSendRequest
 */
export interface EmailSendRequest {
    /**
     * Address is normalized by the server and never logged in full.
     * @type {string}
     * @memberof EmailSendRequest
     */
    email: string;
    /**
     *
     * @type {EmailPurpose}
     * @memberof EmailSendRequest
     */
    purpose: EmailPurpose;
    /**
     *
     * @type {string}
     * @memberof EmailSendRequest
     */
    captchaToken?: string | null;
}



/**
 * Check if a given object implements the EmailSendRequest interface.
 */
export function instanceOfEmailSendRequest(value: object): value is EmailSendRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    return true;
}

export function EmailSendRequestFromJSON(json: any): EmailSendRequest {
    return EmailSendRequestFromJSONTyped(json, false);
}

export function EmailSendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSendRequest {
    if (json == null) {
        return json;
    }
    return {

        'email': json['email'],
        'purpose': EmailPurposeFromJSON(json['purpose']),
        'captchaToken': json['captchaToken'] === undefined ? undefined : json['captchaToken'] === null ? null : json['captchaToken'],
    };
}

export function EmailSendRequestToJSON(json: any): EmailSendRequest {
    return EmailSendRequestToJSONTyped(json, false);
}

export function EmailSendRequestToJSONTyped(value?: EmailSendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'email': value['email'],
        'purpose': EmailPurposeToJSON(value['purpose']),
        'captchaToken': value['captchaToken'],
    };
}
