/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmailChallenge
 */
export interface EmailChallenge {
    /**
     *
     * @type {string}
     * @memberof EmailChallenge
     */
    challengeId: string;
    /**
     *
     * @type {Date}
     * @memberof EmailChallenge
     */
    expiresAt: Date;
    /**
     *
     * @type {number}
     * @memberof EmailChallenge
     */
    resendAfterSeconds: number;
    /**
     * Non-secret display hint that does not disclose account existence.
     * @type {string}
     * @memberof EmailChallenge
     */
    maskedDestination: string;
}

/**
 * Check if a given object implements the EmailChallenge interface.
 */
export function instanceOfEmailChallenge(value: object): value is EmailChallenge {
    if (!('challengeId' in value) || value['challengeId'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('resendAfterSeconds' in value) || value['resendAfterSeconds'] === undefined) return false;
    if (!('maskedDestination' in value) || value['maskedDestination'] === undefined) return false;
    return true;
}

export function EmailChallengeFromJSON(json: any): EmailChallenge {
    return EmailChallengeFromJSONTyped(json, false);
}

export function EmailChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailChallenge {
    if (json == null) {
        return json;
    }
    return {

        'challengeId': json['challengeId'],
        'expiresAt': (new Date(json['expiresAt'])),
        'resendAfterSeconds': json['resendAfterSeconds'],
        'maskedDestination': json['maskedDestination'],
    };
}

export function EmailChallengeToJSON(json: any): EmailChallenge {
    return EmailChallengeToJSONTyped(json, false);
}

export function EmailChallengeToJSONTyped(value?: EmailChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'challengeId': value['challengeId'],
        'expiresAt': value['expiresAt'].toISOString(),
        'resendAfterSeconds': value['resendAfterSeconds'],
        'maskedDestination': value['maskedDestination'],
    };
}
