/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldError } from './FieldError';
import {
    FieldErrorFromJSON,
    FieldErrorFromJSONTyped,
    FieldErrorToJSON,
    FieldErrorToJSONTyped,
} from './FieldError';

/**
 *
 * @export
 * @interface ErrorDetail
 */
export interface ErrorDetail {
    /**
     *
     * @type {boolean}
     * @memberof ErrorDetail
     */
    retryable: boolean;
    /**
     *
     * @type {number}
     * @memberof ErrorDetail
     */
    retryAfterSeconds?: number | null;
    /**
     *
     * @type {Array<FieldError>}
     * @memberof ErrorDetail
     */
    fieldErrors: Array<FieldError>;
    /**
     * Structured non-sensitive error metadata only.
     * @type {{ [key: string]: any; }}
     * @memberof ErrorDetail
     */
    details: { [key: string]: any; };
}

/**
 * Check if a given object implements the ErrorDetail interface.
 */
export function instanceOfErrorDetail(value: object): value is ErrorDetail {
    if (!('retryable' in value) || value['retryable'] === undefined) return false;
    if (!('fieldErrors' in value) || value['fieldErrors'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function ErrorDetailFromJSON(json: any): ErrorDetail {
    return ErrorDetailFromJSONTyped(json, false);
}

export function ErrorDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorDetail {
    if (json == null) {
        return json;
    }
    return {

        'retryable': json['retryable'],
        'retryAfterSeconds': json['retryAfterSeconds'] === undefined ? undefined : json['retryAfterSeconds'] === null ? null : json['retryAfterSeconds'],
        'fieldErrors': ((json['fieldErrors'] as Array<any>).map(FieldErrorFromJSON)),
        'details': json['details'],
    };
}

export function ErrorDetailToJSON(json: any): ErrorDetail {
    return ErrorDetailToJSONTyped(json, false);
}

export function ErrorDetailToJSONTyped(value?: ErrorDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'retryable': value['retryable'],
        'retryAfterSeconds': value['retryAfterSeconds'],
        'fieldErrors': ((value['fieldErrors'] as Array<any>).map(FieldErrorToJSON)),
        'details': value['details'],
    };
}
