/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GenerationAnalysis
 */
export interface GenerationAnalysis {
    /**
     *
     * @type {string}
     * @memberof GenerationAnalysis
     */
    possibleIntent: string;
    /**
     *
     * @type {string}
     * @memberof GenerationAnalysis
     */
    emotion: string;
    /**
     *
     * @type {string}
     * @memberof GenerationAnalysis
     */
    uncertaintyNote: string;
    /**
     *
     * @type {Array<string>}
     * @memberof GenerationAnalysis
     */
    riskTips: Array<string>;
}

/**
 * Check if a given object implements the GenerationAnalysis interface.
 */
export function instanceOfGenerationAnalysis(value: object): value is GenerationAnalysis {
    if (!('possibleIntent' in value) || value['possibleIntent'] === undefined) return false;
    if (!('emotion' in value) || value['emotion'] === undefined) return false;
    if (!('uncertaintyNote' in value) || value['uncertaintyNote'] === undefined) return false;
    if (!('riskTips' in value) || value['riskTips'] === undefined) return false;
    return true;
}

export function GenerationAnalysisFromJSON(json: any): GenerationAnalysis {
    return GenerationAnalysisFromJSONTyped(json, false);
}

export function GenerationAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationAnalysis {
    if (json == null) {
        return json;
    }
    return {

        'possibleIntent': json['possibleIntent'],
        'emotion': json['emotion'],
        'uncertaintyNote': json['uncertaintyNote'],
        'riskTips': json['riskTips'],
    };
}

export function GenerationAnalysisToJSON(json: any): GenerationAnalysis {
    return GenerationAnalysisToJSONTyped(json, false);
}

export function GenerationAnalysisToJSONTyped(value?: GenerationAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'possibleIntent': value['possibleIntent'],
        'emotion': value['emotion'],
        'uncertaintyNote': value['uncertaintyNote'],
        'riskTips': value['riskTips'],
    };
}
