/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChargedFrom } from './ChargedFrom';
import {
    ChargedFromFromJSON,
    ChargedFromFromJSONTyped,
    ChargedFromToJSON,
    ChargedFromToJSONTyped,
} from './ChargedFrom';

/**
 *
 * @export
 * @interface GenerationUsage
 */
export interface GenerationUsage {
    /**
     *
     * @type {string}
     * @memberof GenerationUsage
     */
    modelId: string;
    /**
     *
     * @type {number}
     * @memberof GenerationUsage
     */
    inputTokens: number;
    /**
     *
     * @type {number}
     * @memberof GenerationUsage
     */
    outputTokens: number;
    /**
     *
     * @type {number}
     * @memberof GenerationUsage
     */
    reservedEnergy: number;
    /**
     *
     * @type {number}
     * @memberof GenerationUsage
     */
    chargedEnergy: number;
    /**
     *
     * @type {ChargedFrom}
     * @memberof GenerationUsage
     */
    chargedFrom: ChargedFrom;
}



/**
 * Check if a given object implements the GenerationUsage interface.
 */
export function instanceOfGenerationUsage(value: object): value is GenerationUsage {
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('reservedEnergy' in value) || value['reservedEnergy'] === undefined) return false;
    if (!('chargedEnergy' in value) || value['chargedEnergy'] === undefined) return false;
    if (!('chargedFrom' in value) || value['chargedFrom'] === undefined) return false;
    return true;
}

export function GenerationUsageFromJSON(json: any): GenerationUsage {
    return GenerationUsageFromJSONTyped(json, false);
}

export function GenerationUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationUsage {
    if (json == null) {
        return json;
    }
    return {

        'modelId': json['modelId'],
        'inputTokens': json['inputTokens'],
        'outputTokens': json['outputTokens'],
        'reservedEnergy': json['reservedEnergy'],
        'chargedEnergy': json['chargedEnergy'],
        'chargedFrom': ChargedFromFromJSON(json['chargedFrom']),
    };
}

export function GenerationUsageToJSON(json: any): GenerationUsage {
    return GenerationUsageToJSONTyped(json, false);
}

export function GenerationUsageToJSONTyped(value?: GenerationUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'modelId': value['modelId'],
        'inputTokens': value['inputTokens'],
        'outputTokens': value['outputTokens'],
        'reservedEnergy': value['reservedEnergy'],
        'chargedEnergy': value['chargedEnergy'],
        'chargedFrom': ChargedFromToJSON(value['chargedFrom']),
    };
}
