/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GenerationUsage } from './GenerationUsage';
import {
    instanceOfGenerationUsage,
    GenerationUsageFromJSON,
    GenerationUsageFromJSONTyped,
    GenerationUsageToJSON,
} from './GenerationUsage';

/**
 * @type GenerationSnapshotUsage
 *
 * @export
 */
export type GenerationSnapshotUsage = GenerationUsage | any;

export function GenerationSnapshotUsageFromJSON(json: any): GenerationSnapshotUsage {
    return GenerationSnapshotUsageFromJSONTyped(json, false);
}

export function GenerationSnapshotUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationSnapshotUsage {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGenerationUsage(json)) {
        return GenerationUsageFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GenerationSnapshotUsageToJSON(json: any): any {
    return GenerationSnapshotUsageToJSONTyped(json, false);
}

export function GenerationSnapshotUsageToJSONTyped(value?: GenerationSnapshotUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGenerationUsage(value)) {
        return GenerationUsageToJSON(value as GenerationUsage);
    }
    return {};
}
