/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenerationContext } from './GenerationContext';
import {
    GenerationContextFromJSON,
    GenerationContextFromJSONTyped,
    GenerationContextToJSON,
    GenerationContextToJSONTyped,
} from './GenerationContext';
import type { GenerationInput } from './GenerationInput';
import {
    GenerationInputFromJSON,
    GenerationInputFromJSONTyped,
    GenerationInputToJSON,
    GenerationInputToJSONTyped,
} from './GenerationInput';

/**
 *
 * @export
 * @interface GenerationQuoteRequest
 */
export interface GenerationQuoteRequest {
    /**
     *
     * @type {GenerationInput}
     * @memberof GenerationQuoteRequest
     */
    input: GenerationInput;
    /**
     *
     * @type {GenerationContext}
     * @memberof GenerationQuoteRequest
     */
    context: GenerationContext;
    /**
     *
     * @type {string}
     * @memberof GenerationQuoteRequest
     */
    requestedModelId?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof GenerationQuoteRequest
     */
    saveToHistory: boolean;
}

/**
 * Check if a given object implements the GenerationQuoteRequest interface.
 */
export function instanceOfGenerationQuoteRequest(value: object): value is GenerationQuoteRequest {
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('saveToHistory' in value) || value['saveToHistory'] === undefined) return false;
    return true;
}

export function GenerationQuoteRequestFromJSON(json: any): GenerationQuoteRequest {
    return GenerationQuoteRequestFromJSONTyped(json, false);
}

export function GenerationQuoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationQuoteRequest {
    if (json == null) {
        return json;
    }
    return {

        'input': GenerationInputFromJSON(json['input']),
        'context': GenerationContextFromJSON(json['context']),
        'requestedModelId': json['requestedModelId'] === undefined ? undefined : json['requestedModelId'] === null ? null : json['requestedModelId'],
        'saveToHistory': json['saveToHistory'],
    };
}

export function GenerationQuoteRequestToJSON(json: any): GenerationQuoteRequest {
    return GenerationQuoteRequestToJSONTyped(json, false);
}

export function GenerationQuoteRequestToJSONTyped(value?: GenerationQuoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'input': GenerationInputToJSON(value['input']),
        'context': GenerationContextToJSON(value['context']),
        'requestedModelId': value['requestedModelId'],
        'saveToHistory': value['saveToHistory'],
    };
}
