/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LegalHoldRequest
 */
export interface LegalHoldRequest {
    /**
     *
     * @type {boolean}
     * @memberof LegalHoldRequest
     */
    enabled: boolean;
    /**
     *
     * @type {string}
     * @memberof LegalHoldRequest
     */
    auditReason: string;
}

/**
 * Check if a given object implements the LegalHoldRequest interface.
 */
export function instanceOfLegalHoldRequest(value: object): value is LegalHoldRequest {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    return true;
}

export function LegalHoldRequestFromJSON(json: any): LegalHoldRequest {
    return LegalHoldRequestFromJSONTyped(json, false);
}

export function LegalHoldRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegalHoldRequest {
    if (json == null) {
        return json;
    }
    return {

        'enabled': json['enabled'],
        'auditReason': json['auditReason'],
    };
}

export function LegalHoldRequestToJSON(json: any): LegalHoldRequest {
    return LegalHoldRequestToJSONTyped(json, false);
}

export function LegalHoldRequestToJSONTyped(value?: LegalHoldRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'enabled': value['enabled'],
        'auditReason': value['auditReason'],
    };
}
