/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelQuoteOption
 */
export interface ModelQuoteOption {
    /**
     *
     * @type {string}
     * @memberof ModelQuoteOption
     */
    modelId: string;
    /**
     *
     * @type {number}
     * @memberof ModelQuoteOption
     */
    energyAmount: number;
    /**
     *
     * @type {boolean}
     * @memberof ModelQuoteOption
     */
    available: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ModelQuoteOption
     */
    recommended: boolean;
    /**
     *
     * @type {string}
     * @memberof ModelQuoteOption
     */
    unavailableReasonCode?: string | null;
}

/**
 * Check if a given object implements the ModelQuoteOption interface.
 */
export function instanceOfModelQuoteOption(value: object): value is ModelQuoteOption {
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('energyAmount' in value) || value['energyAmount'] === undefined) return false;
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('recommended' in value) || value['recommended'] === undefined) return false;
    return true;
}

export function ModelQuoteOptionFromJSON(json: any): ModelQuoteOption {
    return ModelQuoteOptionFromJSONTyped(json, false);
}

export function ModelQuoteOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelQuoteOption {
    if (json == null) {
        return json;
    }
    return {

        'modelId': json['modelId'],
        'energyAmount': json['energyAmount'],
        'available': json['available'],
        'recommended': json['recommended'],
        'unavailableReasonCode': json['unavailableReasonCode'] === undefined ? undefined : json['unavailableReasonCode'] === null ? null : json['unavailableReasonCode'],
    };
}

export function ModelQuoteOptionToJSON(json: any): ModelQuoteOption {
    return ModelQuoteOptionToJSONTyped(json, false);
}

export function ModelQuoteOptionToJSONTyped(value?: ModelQuoteOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'modelId': value['modelId'],
        'energyAmount': value['energyAmount'],
        'available': value['available'],
        'recommended': value['recommended'],
        'unavailableReasonCode': value['unavailableReasonCode'],
    };
}
