/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PaymentReconciliation
 */
export interface PaymentReconciliation {
    /**
     *
     * @type {string}
     * @memberof PaymentReconciliation
     */
    reconciliationId: string;
    /**
     *
     * @type {number}
     * @memberof PaymentReconciliation
     */
    scannedCount: number;
    /**
     *
     * @type {number}
     * @memberof PaymentReconciliation
     */
    settledCount: number;
    /**
     *
     * @type {number}
     * @memberof PaymentReconciliation
     */
    recoveredCount: number;
    /**
     *
     * @type {number}
     * @memberof PaymentReconciliation
     */
    conflictCount: number;
    /**
     *
     * @type {Date}
     * @memberof PaymentReconciliation
     */
    startedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof PaymentReconciliation
     */
    completedAt: Date;
}

/**
 * Check if a given object implements the PaymentReconciliation interface.
 */
export function instanceOfPaymentReconciliation(value: object): value is PaymentReconciliation {
    if (!('reconciliationId' in value) || value['reconciliationId'] === undefined) return false;
    if (!('scannedCount' in value) || value['scannedCount'] === undefined) return false;
    if (!('settledCount' in value) || value['settledCount'] === undefined) return false;
    if (!('recoveredCount' in value) || value['recoveredCount'] === undefined) return false;
    if (!('conflictCount' in value) || value['conflictCount'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    return true;
}

export function PaymentReconciliationFromJSON(json: any): PaymentReconciliation {
    return PaymentReconciliationFromJSONTyped(json, false);
}

export function PaymentReconciliationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentReconciliation {
    if (json == null) {
        return json;
    }
    return {

        'reconciliationId': json['reconciliationId'],
        'scannedCount': json['scannedCount'],
        'settledCount': json['settledCount'],
        'recoveredCount': json['recoveredCount'],
        'conflictCount': json['conflictCount'],
        'startedAt': (new Date(json['startedAt'])),
        'completedAt': (new Date(json['completedAt'])),
    };
}

export function PaymentReconciliationToJSON(json: any): PaymentReconciliation {
    return PaymentReconciliationToJSONTyped(json, false);
}

export function PaymentReconciliationToJSONTyped(value?: PaymentReconciliation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'reconciliationId': value['reconciliationId'],
        'scannedCount': value['scannedCount'],
        'settledCount': value['settledCount'],
        'recoveredCount': value['recoveredCount'],
        'conflictCount': value['conflictCount'],
        'startedAt': value['startedAt'].toISOString(),
        'completedAt': value['completedAt'].toISOString(),
    };
}
