/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConsentType } from './ConsentType';
import {
    ConsentTypeFromJSON,
    ConsentTypeFromJSONTyped,
    ConsentTypeToJSON,
    ConsentTypeToJSONTyped,
} from './ConsentType';

/**
 *
 * @export
 * @interface PendingConsent
 */
export interface PendingConsent {
    /**
     *
     * @type {ConsentType}
     * @memberof PendingConsent
     */
    consentType: ConsentType;
    /**
     *
     * @type {string}
     * @memberof PendingConsent
     */
    documentVersion: string;
    /**
     *
     * @type {boolean}
     * @memberof PendingConsent
     */
    required: boolean;
}



/**
 * Check if a given object implements the PendingConsent interface.
 */
export function instanceOfPendingConsent(value: object): value is PendingConsent {
    if (!('consentType' in value) || value['consentType'] === undefined) return false;
    if (!('documentVersion' in value) || value['documentVersion'] === undefined) return false;
    if (!('required' in value) || value['required'] === undefined) return false;
    return true;
}

export function PendingConsentFromJSON(json: any): PendingConsent {
    return PendingConsentFromJSONTyped(json, false);
}

export function PendingConsentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingConsent {
    if (json == null) {
        return json;
    }
    return {

        'consentType': ConsentTypeFromJSON(json['consentType']),
        'documentVersion': json['documentVersion'],
        'required': json['required'],
    };
}

export function PendingConsentToJSON(json: any): PendingConsent {
    return PendingConsentToJSONTyped(json, false);
}

export function PendingConsentToJSONTyped(value?: PendingConsent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'consentType': ConsentTypeToJSON(value['consentType']),
        'documentVersion': value['documentVersion'],
        'required': value['required'],
    };
}
