/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RenewalType } from './RenewalType';
import {
    RenewalTypeFromJSON,
    RenewalTypeFromJSONTyped,
    RenewalTypeToJSON,
    RenewalTypeToJSONTyped,
} from './RenewalType';
import type { BenefitGrant } from './BenefitGrant';
import {
    BenefitGrantFromJSON,
    BenefitGrantFromJSONTyped,
    BenefitGrantToJSON,
    BenefitGrantToJSONTyped,
} from './BenefitGrant';

/**
 *
 * @export
 * @interface ProductOrderSnapshot
 */
export interface ProductOrderSnapshot {
    /**
     *
     * @type {string}
     * @memberof ProductOrderSnapshot
     */
    productVersionId: string;
    /**
     *
     * @type {string}
     * @memberof ProductOrderSnapshot
     */
    productCode: string;
    /**
     *
     * @type {number}
     * @memberof ProductOrderSnapshot
     */
    version: number;
    /**
     *
     * @type {string}
     * @memberof ProductOrderSnapshot
     */
    displayName: string;
    /**
     *
     * @type {string}
     * @memberof ProductOrderSnapshot
     */
    currency: string;
    /**
     *
     * @type {number}
     * @memberof ProductOrderSnapshot
     */
    amountMinor: number;
    /**
     *
     * @type {RenewalType}
     * @memberof ProductOrderSnapshot
     */
    renewalType: RenewalType;
    /**
     *
     * @type {number}
     * @memberof ProductOrderSnapshot
     */
    termDays: number | null;
    /**
     *
     * @type {number}
     * @memberof ProductOrderSnapshot
     */
    benefitWindowDays: number;
    /**
     *
     * @type {BenefitGrant}
     * @memberof ProductOrderSnapshot
     */
    benefits: BenefitGrant;
}



/**
 * Check if a given object implements the ProductOrderSnapshot interface.
 */
export function instanceOfProductOrderSnapshot(value: object): value is ProductOrderSnapshot {
    if (!('productVersionId' in value) || value['productVersionId'] === undefined) return false;
    if (!('productCode' in value) || value['productCode'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amountMinor' in value) || value['amountMinor'] === undefined) return false;
    if (!('renewalType' in value) || value['renewalType'] === undefined) return false;
    if (!('termDays' in value) || value['termDays'] === undefined) return false;
    if (!('benefitWindowDays' in value) || value['benefitWindowDays'] === undefined) return false;
    if (!('benefits' in value) || value['benefits'] === undefined) return false;
    return true;
}

export function ProductOrderSnapshotFromJSON(json: any): ProductOrderSnapshot {
    return ProductOrderSnapshotFromJSONTyped(json, false);
}

export function ProductOrderSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOrderSnapshot {
    if (json == null) {
        return json;
    }
    return {

        'productVersionId': json['productVersionId'],
        'productCode': json['productCode'],
        'version': json['version'],
        'displayName': json['displayName'],
        'currency': json['currency'],
        'amountMinor': json['amountMinor'],
        'renewalType': RenewalTypeFromJSON(json['renewalType']),
        'termDays': json['termDays'],
        'benefitWindowDays': json['benefitWindowDays'],
        'benefits': BenefitGrantFromJSON(json['benefits']),
    };
}

export function ProductOrderSnapshotToJSON(json: any): ProductOrderSnapshot {
    return ProductOrderSnapshotToJSONTyped(json, false);
}

export function ProductOrderSnapshotToJSONTyped(value?: ProductOrderSnapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'productVersionId': value['productVersionId'],
        'productCode': value['productCode'],
        'version': value['version'],
        'displayName': value['displayName'],
        'currency': value['currency'],
        'amountMinor': value['amountMinor'],
        'renewalType': RenewalTypeToJSON(value['renewalType']),
        'termDays': value['termDays'],
        'benefitWindowDays': value['benefitWindowDays'],
        'benefits': BenefitGrantToJSON(value['benefits']),
    };
}
