/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductVersion } from './ProductVersion';
import {
    ProductVersionFromJSON,
    ProductVersionFromJSONTyped,
    ProductVersionToJSON,
    ProductVersionToJSONTyped,
} from './ProductVersion';

/**
 *
 * @export
 * @interface ProductListData
 */
export interface ProductListData {
    /**
     *
     * @type {number}
     * @memberof ProductListData
     */
    catalogVersion: number;
    /**
     *
     * @type {Array<ProductVersion>}
     * @memberof ProductListData
     */
    items: Array<ProductVersion>;
}

/**
 * Check if a given object implements the ProductListData interface.
 */
export function instanceOfProductListData(value: object): value is ProductListData {
    if (!('catalogVersion' in value) || value['catalogVersion'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ProductListDataFromJSON(json: any): ProductListData {
    return ProductListDataFromJSONTyped(json, false);
}

export function ProductListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListData {
    if (json == null) {
        return json;
    }
    return {

        'catalogVersion': json['catalogVersion'],
        'items': ((json['items'] as Array<any>).map(ProductVersionFromJSON)),
    };
}

export function ProductListDataToJSON(json: any): ProductListData {
    return ProductListDataToJSONTyped(json, false);
}

export function ProductListDataToJSONTyped(value?: ProductListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'catalogVersion': value['catalogVersion'],
        'items': ((value['items'] as Array<any>).map(ProductVersionToJSON)),
    };
}
