/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductVersion } from './ProductVersion';
import {
    ProductVersionFromJSON,
    ProductVersionFromJSONTyped,
    ProductVersionToJSON,
    ProductVersionToJSONTyped,
} from './ProductVersion';

/**
 *
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     *
     * @type {string}
     * @memberof ProductResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ProductResponse
     */
    message: string;
    /**
     *
     * @type {ProductVersion}
     * @memberof ProductResponse
     */
    data: ProductVersion;
    /**
     *
     * @type {string}
     * @memberof ProductResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof ProductResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ProductResponse interface.
 */
export function instanceOfProductResponse(value: object): value is ProductResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ProductResponseFromJSON(json: any): ProductResponse {
    return ProductResponseFromJSONTyped(json, false);
}

export function ProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': ProductVersionFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ProductResponseToJSON(json: any): ProductResponse {
    return ProductResponseToJSONTyped(json, false);
}

export function ProductResponseToJSONTyped(value?: ProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': ProductVersionToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
