/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesChannel } from './SalesChannel';
import {
    SalesChannelFromJSON,
    SalesChannelFromJSONTyped,
    SalesChannelToJSON,
    SalesChannelToJSONTyped,
} from './SalesChannel';
import type { ProductPublicationStatus } from './ProductPublicationStatus';
import {
    ProductPublicationStatusFromJSON,
    ProductPublicationStatusFromJSONTyped,
    ProductPublicationStatusToJSON,
    ProductPublicationStatusToJSONTyped,
} from './ProductPublicationStatus';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
    ProductTypeToJSONTyped,
} from './ProductType';
import type { RenewalType } from './RenewalType';
import {
    RenewalTypeFromJSON,
    RenewalTypeFromJSONTyped,
    RenewalTypeToJSON,
    RenewalTypeToJSONTyped,
} from './RenewalType';
import type { BenefitGrant } from './BenefitGrant';
import {
    BenefitGrantFromJSON,
    BenefitGrantFromJSONTyped,
    BenefitGrantToJSON,
    BenefitGrantToJSONTyped,
} from './BenefitGrant';

/**
 *
 * @export
 * @interface ProductVersion
 */
export interface ProductVersion {
    /**
     *
     * @type {string}
     * @memberof ProductVersion
     */
    productVersionId: string;
    /**
     *
     * @type {string}
     * @memberof ProductVersion
     */
    productCode: string;
    /**
     *
     * @type {number}
     * @memberof ProductVersion
     */
    version: number;
    /**
     *
     * @type {ProductType}
     * @memberof ProductVersion
     */
    productType: ProductType;
    /**
     *
     * @type {string}
     * @memberof ProductVersion
     */
    displayName: string;
    /**
     *
     * @type {string}
     * @memberof ProductVersion
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProductVersion
     */
    currency: string;
    /**
     *
     * @type {number}
     * @memberof ProductVersion
     */
    amountMinor: number;
    /**
     *
     * @type {string}
     * @memberof ProductVersion
     */
    region: string;
    /**
     *
     * @type {Set<SalesChannel>}
     * @memberof ProductVersion
     */
    salesChannels: Set<SalesChannel>;
    /**
     *
     * @type {RenewalType}
     * @memberof ProductVersion
     */
    renewalType: RenewalType;
    /**
     *
     * @type {number}
     * @memberof ProductVersion
     */
    termDays?: number | null;
    /**
     *
     * @type {number}
     * @memberof ProductVersion
     */
    benefitWindowDays: number;
    /**
     *
     * @type {BenefitGrant}
     * @memberof ProductVersion
     */
    benefits: BenefitGrant;
    /**
     *
     * @type {ProductPublicationStatus}
     * @memberof ProductVersion
     */
    status: ProductPublicationStatus;
    /**
     *
     * @type {Date}
     * @memberof ProductVersion
     */
    effectiveAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ProductVersion
     */
    expiresAt?: Date | null;
}



/**
 * Check if a given object implements the ProductVersion interface.
 */
export function instanceOfProductVersion(value: object): value is ProductVersion {
    if (!('productVersionId' in value) || value['productVersionId'] === undefined) return false;
    if (!('productCode' in value) || value['productCode'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('productType' in value) || value['productType'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amountMinor' in value) || value['amountMinor'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('salesChannels' in value) || value['salesChannels'] === undefined) return false;
    if (!('renewalType' in value) || value['renewalType'] === undefined) return false;
    if (!('benefitWindowDays' in value) || value['benefitWindowDays'] === undefined) return false;
    if (!('benefits' in value) || value['benefits'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('effectiveAt' in value) || value['effectiveAt'] === undefined) return false;
    return true;
}

export function ProductVersionFromJSON(json: any): ProductVersion {
    return ProductVersionFromJSONTyped(json, false);
}

export function ProductVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVersion {
    if (json == null) {
        return json;
    }
    return {

        'productVersionId': json['productVersionId'],
        'productCode': json['productCode'],
        'version': json['version'],
        'productType': ProductTypeFromJSON(json['productType']),
        'displayName': json['displayName'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'currency': json['currency'],
        'amountMinor': json['amountMinor'],
        'region': json['region'],
        'salesChannels': (new Set((json['salesChannels'] as Array<any>).map(SalesChannelFromJSON))),
        'renewalType': RenewalTypeFromJSON(json['renewalType']),
        'termDays': json['termDays'] === undefined ? undefined : json['termDays'] === null ? null : json['termDays'],
        'benefitWindowDays': json['benefitWindowDays'],
        'benefits': BenefitGrantFromJSON(json['benefits']),
        'status': ProductPublicationStatusFromJSON(json['status']),
        'effectiveAt': (new Date(json['effectiveAt'])),
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : (new Date(json['expiresAt'])),
    };
}

export function ProductVersionToJSON(json: any): ProductVersion {
    return ProductVersionToJSONTyped(json, false);
}

export function ProductVersionToJSONTyped(value?: ProductVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'productVersionId': value['productVersionId'],
        'productCode': value['productCode'],
        'version': value['version'],
        'productType': ProductTypeToJSON(value['productType']),
        'displayName': value['displayName'],
        'description': value['description'],
        'currency': value['currency'],
        'amountMinor': value['amountMinor'],
        'region': value['region'],
        'salesChannels': (Array.from(value['salesChannels'] as Set<any>).map(SalesChannelToJSON)),
        'renewalType': RenewalTypeToJSON(value['renewalType']),
        'termDays': value['termDays'],
        'benefitWindowDays': value['benefitWindowDays'],
        'benefits': BenefitGrantToJSON(value['benefits']),
        'status': ProductPublicationStatusToJSON(value['status']),
        'effectiveAt': value['effectiveAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}
