/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PublishProviderRequest
 */
export interface PublishProviderRequest {
    /**
     *
     * @type {number}
     * @memberof PublishProviderRequest
     */
    rolloutPercentage: number;
    /**
     *
     * @type {Date}
     * @memberof PublishProviderRequest
     */
    effectiveAt: Date;
    /**
     *
     * @type {string}
     * @memberof PublishProviderRequest
     */
    auditReason: string;
}

/**
 * Check if a given object implements the PublishProviderRequest interface.
 */
export function instanceOfPublishProviderRequest(value: object): value is PublishProviderRequest {
    if (!('rolloutPercentage' in value) || value['rolloutPercentage'] === undefined) return false;
    if (!('effectiveAt' in value) || value['effectiveAt'] === undefined) return false;
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    return true;
}

export function PublishProviderRequestFromJSON(json: any): PublishProviderRequest {
    return PublishProviderRequestFromJSONTyped(json, false);
}

export function PublishProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishProviderRequest {
    if (json == null) {
        return json;
    }
    return {

        'rolloutPercentage': json['rolloutPercentage'],
        'effectiveAt': (new Date(json['effectiveAt'])),
        'auditReason': json['auditReason'],
    };
}

export function PublishProviderRequestToJSON(json: any): PublishProviderRequest {
    return PublishProviderRequestToJSONTyped(json, false);
}

export function PublishProviderRequestToJSONTyped(value?: PublishProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'rolloutPercentage': value['rolloutPercentage'],
        'effectiveAt': value['effectiveAt'].toISOString(),
        'auditReason': value['auditReason'],
    };
}
