/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferralInviteListData } from './ReferralInviteListData';
import {
    ReferralInviteListDataFromJSON,
    ReferralInviteListDataFromJSONTyped,
    ReferralInviteListDataToJSON,
    ReferralInviteListDataToJSONTyped,
} from './ReferralInviteListData';

/**
 *
 * @export
 * @interface ReferralInviteListResponse
 */
export interface ReferralInviteListResponse {
    /**
     *
     * @type {string}
     * @memberof ReferralInviteListResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ReferralInviteListResponse
     */
    message: string;
    /**
     *
     * @type {ReferralInviteListData}
     * @memberof ReferralInviteListResponse
     */
    data: ReferralInviteListData;
    /**
     *
     * @type {string}
     * @memberof ReferralInviteListResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof ReferralInviteListResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ReferralInviteListResponse interface.
 */
export function instanceOfReferralInviteListResponse(value: object): value is ReferralInviteListResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ReferralInviteListResponseFromJSON(json: any): ReferralInviteListResponse {
    return ReferralInviteListResponseFromJSONTyped(json, false);
}

export function ReferralInviteListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralInviteListResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': ReferralInviteListDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ReferralInviteListResponseToJSON(json: any): ReferralInviteListResponse {
    return ReferralInviteListResponseToJSONTyped(json, false);
}

export function ReferralInviteListResponseToJSONTyped(value?: ReferralInviteListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': ReferralInviteListDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
