/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesChannel } from './SalesChannel';
import {
    SalesChannelFromJSON,
    SalesChannelFromJSONTyped,
    SalesChannelToJSON,
    SalesChannelToJSONTyped,
} from './SalesChannel';
import type { ReferralAntiAbusePolicy } from './ReferralAntiAbusePolicy';
import {
    ReferralAntiAbusePolicyFromJSON,
    ReferralAntiAbusePolicyFromJSONTyped,
    ReferralAntiAbusePolicyToJSON,
    ReferralAntiAbusePolicyToJSONTyped,
} from './ReferralAntiAbusePolicy';
import type { ReferralCampaignStatus } from './ReferralCampaignStatus';
import {
    ReferralCampaignStatusFromJSON,
    ReferralCampaignStatusFromJSONTyped,
    ReferralCampaignStatusToJSON,
    ReferralCampaignStatusToJSONTyped,
} from './ReferralCampaignStatus';
import type { ReferralRewardRule } from './ReferralRewardRule';
import {
    ReferralRewardRuleFromJSON,
    ReferralRewardRuleFromJSONTyped,
    ReferralRewardRuleToJSON,
    ReferralRewardRuleToJSONTyped,
} from './ReferralRewardRule';

/**
 *
 * @export
 * @interface ReferralCampaign
 */
export interface ReferralCampaign {
    /**
     *
     * @type {string}
     * @memberof ReferralCampaign
     */
    campaignId: string;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaign
     */
    version: number;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaign
     */
    campaignCode: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaign
     */
    displayName: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaign
     */
    description: string;
    /**
     *
     * @type {ReferralCampaignStatus}
     * @memberof ReferralCampaign
     */
    status: ReferralCampaignStatus;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaign
     */
    region: string;
    /**
     *
     * @type {Set<SalesChannel>}
     * @memberof ReferralCampaign
     */
    salesChannels: Set<SalesChannel>;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaign
     */
    bindingWindowHours: number;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaign
     */
    maxQualifiedInvitesPerInviter: number;
    /**
     *
     * @type {Array<ReferralRewardRule>}
     * @memberof ReferralCampaign
     */
    rewardRules: Array<ReferralRewardRule>;
    /**
     *
     * @type {ReferralAntiAbusePolicy}
     * @memberof ReferralCampaign
     */
    antiAbusePolicy: ReferralAntiAbusePolicy;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaign
     */
    rolloutPercentage: number;
    /**
     *
     * @type {Date}
     * @memberof ReferralCampaign
     */
    effectiveAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ReferralCampaign
     */
    expiresAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaign
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof ReferralCampaign
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ReferralCampaign
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ReferralCampaign interface.
 */
export function instanceOfReferralCampaign(value: object): value is ReferralCampaign {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('campaignCode' in value) || value['campaignCode'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('salesChannels' in value) || value['salesChannels'] === undefined) return false;
    if (!('bindingWindowHours' in value) || value['bindingWindowHours'] === undefined) return false;
    if (!('maxQualifiedInvitesPerInviter' in value) || value['maxQualifiedInvitesPerInviter'] === undefined) return false;
    if (!('rewardRules' in value) || value['rewardRules'] === undefined) return false;
    if (!('antiAbusePolicy' in value) || value['antiAbusePolicy'] === undefined) return false;
    if (!('rolloutPercentage' in value) || value['rolloutPercentage'] === undefined) return false;
    if (!('effectiveAt' in value) || value['effectiveAt'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ReferralCampaignFromJSON(json: any): ReferralCampaign {
    return ReferralCampaignFromJSONTyped(json, false);
}

export function ReferralCampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralCampaign {
    if (json == null) {
        return json;
    }
    return {

        'campaignId': json['campaignId'],
        'version': json['version'],
        'campaignCode': json['campaignCode'],
        'displayName': json['displayName'],
        'description': json['description'],
        'status': ReferralCampaignStatusFromJSON(json['status']),
        'region': json['region'],
        'salesChannels': (new Set((json['salesChannels'] as Array<any>).map(SalesChannelFromJSON))),
        'bindingWindowHours': json['bindingWindowHours'],
        'maxQualifiedInvitesPerInviter': json['maxQualifiedInvitesPerInviter'],
        'rewardRules': ((json['rewardRules'] as Array<any>).map(ReferralRewardRuleFromJSON)),
        'antiAbusePolicy': ReferralAntiAbusePolicyFromJSON(json['antiAbusePolicy']),
        'rolloutPercentage': json['rolloutPercentage'],
        'effectiveAt': (new Date(json['effectiveAt'])),
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : (new Date(json['expiresAt'])),
        'resourceVersion': json['resourceVersion'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ReferralCampaignToJSON(json: any): ReferralCampaign {
    return ReferralCampaignToJSONTyped(json, false);
}

export function ReferralCampaignToJSONTyped(value?: ReferralCampaign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'campaignId': value['campaignId'],
        'version': value['version'],
        'campaignCode': value['campaignCode'],
        'displayName': value['displayName'],
        'description': value['description'],
        'status': ReferralCampaignStatusToJSON(value['status']),
        'region': value['region'],
        'salesChannels': (Array.from(value['salesChannels'] as Set<any>).map(SalesChannelToJSON)),
        'bindingWindowHours': value['bindingWindowHours'],
        'maxQualifiedInvitesPerInviter': value['maxQualifiedInvitesPerInviter'],
        'rewardRules': ((value['rewardRules'] as Array<any>).map(ReferralRewardRuleToJSON)),
        'antiAbusePolicy': ReferralAntiAbusePolicyToJSON(value['antiAbusePolicy']),
        'rolloutPercentage': value['rolloutPercentage'],
        'effectiveAt': value['effectiveAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'resourceVersion': value['resourceVersion'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
