/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferralMilestoneCode } from './ReferralMilestoneCode';
import {
    ReferralMilestoneCodeFromJSON,
    ReferralMilestoneCodeFromJSONTyped,
    ReferralMilestoneCodeToJSON,
    ReferralMilestoneCodeToJSONTyped,
} from './ReferralMilestoneCode';
import type { ReferralInviteStatus } from './ReferralInviteStatus';
import {
    ReferralInviteStatusFromJSON,
    ReferralInviteStatusFromJSONTyped,
    ReferralInviteStatusToJSON,
    ReferralInviteStatusToJSONTyped,
} from './ReferralInviteStatus';

/**
 *
 * @export
 * @interface ReferralInvite
 */
export interface ReferralInvite {
    /**
     *
     * @type {string}
     * @memberof ReferralInvite
     */
    referralId: string;
    /**
     *
     * @type {string}
     * @memberof ReferralInvite
     */
    campaignId: string;
    /**
     *
     * @type {number}
     * @memberof ReferralInvite
     */
    campaignVersion: number;
    /**
     * Irreversible masked hint; email address or phone number is never returned.
     * @type {string}
     * @memberof ReferralInvite
     */
    inviteeDisplayHint: string;
    /**
     *
     * @type {ReferralInviteStatus}
     * @memberof ReferralInvite
     */
    status: ReferralInviteStatus;
    /**
     *
     * @type {Set<ReferralMilestoneCode>}
     * @memberof ReferralInvite
     */
    completedMilestones: Set<ReferralMilestoneCode>;
    /**
     *
     * @type {string}
     * @memberof ReferralInvite
     */
    rejectionReasonCode?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ReferralInvite
     */
    boundAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ReferralInvite
     */
    qualifiedAt?: Date | null;
    /**
     *
     * @type {number}
     * @memberof ReferralInvite
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof ReferralInvite
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ReferralInvite interface.
 */
export function instanceOfReferralInvite(value: object): value is ReferralInvite {
    if (!('referralId' in value) || value['referralId'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('campaignVersion' in value) || value['campaignVersion'] === undefined) return false;
    if (!('inviteeDisplayHint' in value) || value['inviteeDisplayHint'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('completedMilestones' in value) || value['completedMilestones'] === undefined) return false;
    if (!('boundAt' in value) || value['boundAt'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ReferralInviteFromJSON(json: any): ReferralInvite {
    return ReferralInviteFromJSONTyped(json, false);
}

export function ReferralInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralInvite {
    if (json == null) {
        return json;
    }
    return {

        'referralId': json['referralId'],
        'campaignId': json['campaignId'],
        'campaignVersion': json['campaignVersion'],
        'inviteeDisplayHint': json['inviteeDisplayHint'],
        'status': ReferralInviteStatusFromJSON(json['status']),
        'completedMilestones': (new Set((json['completedMilestones'] as Array<any>).map(ReferralMilestoneCodeFromJSON))),
        'rejectionReasonCode': json['rejectionReasonCode'] === undefined ? undefined : json['rejectionReasonCode'] === null ? null : json['rejectionReasonCode'],
        'boundAt': (new Date(json['boundAt'])),
        'qualifiedAt': json['qualifiedAt'] === undefined ? undefined : json['qualifiedAt'] === null ? null : (new Date(json['qualifiedAt'])),
        'resourceVersion': json['resourceVersion'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ReferralInviteToJSON(json: any): ReferralInvite {
    return ReferralInviteToJSONTyped(json, false);
}

export function ReferralInviteToJSONTyped(value?: ReferralInvite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'referralId': value['referralId'],
        'campaignId': value['campaignId'],
        'campaignVersion': value['campaignVersion'],
        'inviteeDisplayHint': value['inviteeDisplayHint'],
        'status': ReferralInviteStatusToJSON(value['status']),
        'completedMilestones': (Array.from(value['completedMilestones'] as Set<any>).map(ReferralMilestoneCodeToJSON)),
        'rejectionReasonCode': value['rejectionReasonCode'],
        'boundAt': value['boundAt'].toISOString(),
        'qualifiedAt': value['qualifiedAt'] == null ? value['qualifiedAt'] : value['qualifiedAt'].toISOString(),
        'resourceVersion': value['resourceVersion'],
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
