/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferralMilestoneCode } from './ReferralMilestoneCode';
import {
    ReferralMilestoneCodeFromJSON,
    ReferralMilestoneCodeFromJSONTyped,
    ReferralMilestoneCodeToJSON,
    ReferralMilestoneCodeToJSONTyped,
} from './ReferralMilestoneCode';
import type { RewardUnit } from './RewardUnit';
import {
    RewardUnitFromJSON,
    RewardUnitFromJSONTyped,
    RewardUnitToJSON,
    RewardUnitToJSONTyped,
} from './RewardUnit';
import type { ReferralRewardStatus } from './ReferralRewardStatus';
import {
    ReferralRewardStatusFromJSON,
    ReferralRewardStatusFromJSONTyped,
    ReferralRewardStatusToJSON,
    ReferralRewardStatusToJSONTyped,
} from './ReferralRewardStatus';
import type { ReferralBeneficiary } from './ReferralBeneficiary';
import {
    ReferralBeneficiaryFromJSON,
    ReferralBeneficiaryFromJSONTyped,
    ReferralBeneficiaryToJSON,
    ReferralBeneficiaryToJSONTyped,
} from './ReferralBeneficiary';

/**
 *
 * @export
 * @interface ReferralReward
 */
export interface ReferralReward {
    /**
     *
     * @type {string}
     * @memberof ReferralReward
     */
    referralRewardId: string;
    /**
     *
     * @type {string}
     * @memberof ReferralReward
     */
    referralId: string;
    /**
     *
     * @type {ReferralBeneficiary}
     * @memberof ReferralReward
     */
    beneficiary: ReferralBeneficiary;
    /**
     *
     * @type {ReferralMilestoneCode}
     * @memberof ReferralReward
     */
    milestoneCode: ReferralMilestoneCode;
    /**
     *
     * @type {RewardUnit}
     * @memberof ReferralReward
     */
    rewardUnit: RewardUnit;
    /**
     *
     * @type {number}
     * @memberof ReferralReward
     */
    rewardAmount: number;
    /**
     *
     * @type {ReferralRewardStatus}
     * @memberof ReferralReward
     */
    status: ReferralRewardStatus;
    /**
     *
     * @type {string}
     * @memberof ReferralReward
     */
    walletLedgerEntryId?: string | null;
    /**
     *
     * @type {string}
     * @memberof ReferralReward
     */
    entitlementEventId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof ReferralReward
     */
    availableAt?: Date | null;
    /**
     *
     * @type {Date}
     * @memberof ReferralReward
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ReferralReward
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ReferralReward interface.
 */
export function instanceOfReferralReward(value: object): value is ReferralReward {
    if (!('referralRewardId' in value) || value['referralRewardId'] === undefined) return false;
    if (!('referralId' in value) || value['referralId'] === undefined) return false;
    if (!('beneficiary' in value) || value['beneficiary'] === undefined) return false;
    if (!('milestoneCode' in value) || value['milestoneCode'] === undefined) return false;
    if (!('rewardUnit' in value) || value['rewardUnit'] === undefined) return false;
    if (!('rewardAmount' in value) || value['rewardAmount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ReferralRewardFromJSON(json: any): ReferralReward {
    return ReferralRewardFromJSONTyped(json, false);
}

export function ReferralRewardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralReward {
    if (json == null) {
        return json;
    }
    return {

        'referralRewardId': json['referralRewardId'],
        'referralId': json['referralId'],
        'beneficiary': ReferralBeneficiaryFromJSON(json['beneficiary']),
        'milestoneCode': ReferralMilestoneCodeFromJSON(json['milestoneCode']),
        'rewardUnit': RewardUnitFromJSON(json['rewardUnit']),
        'rewardAmount': json['rewardAmount'],
        'status': ReferralRewardStatusFromJSON(json['status']),
        'walletLedgerEntryId': json['walletLedgerEntryId'] === undefined ? undefined : json['walletLedgerEntryId'] === null ? null : json['walletLedgerEntryId'],
        'entitlementEventId': json['entitlementEventId'] === undefined ? undefined : json['entitlementEventId'] === null ? null : json['entitlementEventId'],
        'availableAt': json['availableAt'] === undefined ? undefined : json['availableAt'] === null ? null : (new Date(json['availableAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ReferralRewardToJSON(json: any): ReferralReward {
    return ReferralRewardToJSONTyped(json, false);
}

export function ReferralRewardToJSONTyped(value?: ReferralReward | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'referralRewardId': value['referralRewardId'],
        'referralId': value['referralId'],
        'beneficiary': ReferralBeneficiaryToJSON(value['beneficiary']),
        'milestoneCode': ReferralMilestoneCodeToJSON(value['milestoneCode']),
        'rewardUnit': RewardUnitToJSON(value['rewardUnit']),
        'rewardAmount': value['rewardAmount'],
        'status': ReferralRewardStatusToJSON(value['status']),
        'walletLedgerEntryId': value['walletLedgerEntryId'],
        'entitlementEventId': value['entitlementEventId'],
        'availableAt': value['availableAt'] == null ? value['availableAt'] : value['availableAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
