/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const ReferralRewardStatus = {
    Pending: 'PENDING',
    Granted: 'GRANTED',
    Rejected: 'REJECTED',
    Reversed: 'REVERSED'
} as const;
export type ReferralRewardStatus = typeof ReferralRewardStatus[keyof typeof ReferralRewardStatus];


export function instanceOfReferralRewardStatus(value: any): boolean {
    for (const key in ReferralRewardStatus) {
        if (Object.prototype.hasOwnProperty.call(ReferralRewardStatus, key)) {
            if (ReferralRewardStatus[key as keyof typeof ReferralRewardStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReferralRewardStatusFromJSON(json: any): ReferralRewardStatus {
    return ReferralRewardStatusFromJSONTyped(json, false);
}

export function ReferralRewardStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralRewardStatus {
    return json as ReferralRewardStatus;
}

export function ReferralRewardStatusToJSON(value?: ReferralRewardStatus | null): any {
    return value as any;
}

export function ReferralRewardStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ReferralRewardStatus {
    return value as ReferralRewardStatus;
}
