/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferralInvite } from './ReferralInvite';
import {
    ReferralInviteFromJSON,
    ReferralInviteFromJSONTyped,
    ReferralInviteToJSON,
    ReferralInviteToJSONTyped,
} from './ReferralInvite';

/**
 *
 * @export
 * @interface ReferralInviteResponse
 */
export interface ReferralInviteResponse {
    /**
     *
     * @type {string}
     * @memberof ReferralInviteResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ReferralInviteResponse
     */
    message: string;
    /**
     *
     * @type {ReferralInvite}
     * @memberof ReferralInviteResponse
     */
    data: ReferralInvite;
    /**
     *
     * @type {string}
     * @memberof ReferralInviteResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof ReferralInviteResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the ReferralInviteResponse interface.
 */
export function instanceOfReferralInviteResponse(value: object): value is ReferralInviteResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ReferralInviteResponseFromJSON(json: any): ReferralInviteResponse {
    return ReferralInviteResponseFromJSONTyped(json, false);
}

export function ReferralInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralInviteResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': ReferralInviteFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function ReferralInviteResponseToJSON(json: any): ReferralInviteResponse {
    return ReferralInviteResponseToJSONTyped(json, false);
}

export function ReferralInviteResponseToJSONTyped(value?: ReferralInviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': ReferralInviteToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
