/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesChannel } from './SalesChannel';
import {
    SalesChannelFromJSON,
    SalesChannelFromJSONTyped,
    SalesChannelToJSON,
    SalesChannelToJSONTyped,
} from './SalesChannel';
import type { ReferralAntiAbusePolicy } from './ReferralAntiAbusePolicy';
import {
    ReferralAntiAbusePolicyFromJSON,
    ReferralAntiAbusePolicyFromJSONTyped,
    ReferralAntiAbusePolicyToJSON,
    ReferralAntiAbusePolicyToJSONTyped,
} from './ReferralAntiAbusePolicy';
import type { ReferralRewardRule } from './ReferralRewardRule';
import {
    ReferralRewardRuleFromJSON,
    ReferralRewardRuleFromJSONTyped,
    ReferralRewardRuleToJSON,
    ReferralRewardRuleToJSONTyped,
} from './ReferralRewardRule';

/**
 *
 * @export
 * @interface ReferralCampaignVersion
 */
export interface ReferralCampaignVersion {
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    campaignVersionId: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    campaignId: string;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaignVersion
     */
    version: number;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    campaignCode: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    displayName: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    description: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    region: string;
    /**
     *
     * @type {Array<SalesChannel>}
     * @memberof ReferralCampaignVersion
     */
    salesChannels: Array<SalesChannel>;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaignVersion
     */
    bindingWindowHours: number;
    /**
     *
     * @type {number}
     * @memberof ReferralCampaignVersion
     */
    maxQualifiedInvitesPerInviter: number;
    /**
     *
     * @type {Array<ReferralRewardRule>}
     * @memberof ReferralCampaignVersion
     */
    rewardRules: Array<ReferralRewardRule>;
    /**
     *
     * @type {ReferralAntiAbusePolicy}
     * @memberof ReferralCampaignVersion
     */
    antiAbusePolicy: ReferralAntiAbusePolicy;
    /**
     *
     * @type {boolean}
     * @memberof ReferralCampaignVersion
     */
    wasPublished: boolean;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    action: string;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignVersion
     */
    createdByAdminId: string;
    /**
     *
     * @type {Date}
     * @memberof ReferralCampaignVersion
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ReferralCampaignVersion interface.
 */
export function instanceOfReferralCampaignVersion(value: object): value is ReferralCampaignVersion {
    if (!('campaignVersionId' in value) || value['campaignVersionId'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('campaignCode' in value) || value['campaignCode'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('salesChannels' in value) || value['salesChannels'] === undefined) return false;
    if (!('bindingWindowHours' in value) || value['bindingWindowHours'] === undefined) return false;
    if (!('maxQualifiedInvitesPerInviter' in value) || value['maxQualifiedInvitesPerInviter'] === undefined) return false;
    if (!('rewardRules' in value) || value['rewardRules'] === undefined) return false;
    if (!('antiAbusePolicy' in value) || value['antiAbusePolicy'] === undefined) return false;
    if (!('wasPublished' in value) || value['wasPublished'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('createdByAdminId' in value) || value['createdByAdminId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReferralCampaignVersionFromJSON(json: any): ReferralCampaignVersion {
    return ReferralCampaignVersionFromJSONTyped(json, false);
}

export function ReferralCampaignVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralCampaignVersion {
    if (json == null) {
        return json;
    }
    return {

        'campaignVersionId': json['campaignVersionId'],
        'campaignId': json['campaignId'],
        'version': json['version'],
        'campaignCode': json['campaignCode'],
        'displayName': json['displayName'],
        'description': json['description'],
        'region': json['region'],
        'salesChannels': ((json['salesChannels'] as Array<any>).map(SalesChannelFromJSON)),
        'bindingWindowHours': json['bindingWindowHours'],
        'maxQualifiedInvitesPerInviter': json['maxQualifiedInvitesPerInviter'],
        'rewardRules': ((json['rewardRules'] as Array<any>).map(ReferralRewardRuleFromJSON)),
        'antiAbusePolicy': ReferralAntiAbusePolicyFromJSON(json['antiAbusePolicy']),
        'wasPublished': json['wasPublished'],
        'action': json['action'],
        'createdByAdminId': json['createdByAdminId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ReferralCampaignVersionToJSON(json: any): ReferralCampaignVersion {
    return ReferralCampaignVersionToJSONTyped(json, false);
}

export function ReferralCampaignVersionToJSONTyped(value?: ReferralCampaignVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'campaignVersionId': value['campaignVersionId'],
        'campaignId': value['campaignId'],
        'version': value['version'],
        'campaignCode': value['campaignCode'],
        'displayName': value['displayName'],
        'description': value['description'],
        'region': value['region'],
        'salesChannels': ((value['salesChannels'] as Array<any>).map(SalesChannelToJSON)),
        'bindingWindowHours': value['bindingWindowHours'],
        'maxQualifiedInvitesPerInviter': value['maxQualifiedInvitesPerInviter'],
        'rewardRules': ((value['rewardRules'] as Array<any>).map(ReferralRewardRuleToJSON)),
        'antiAbusePolicy': ReferralAntiAbusePolicyToJSON(value['antiAbusePolicy']),
        'wasPublished': value['wasPublished'],
        'action': value['action'],
        'createdByAdminId': value['createdByAdminId'],
        'createdAt': value['createdAt'].toISOString(),
    };
}
