/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const ReferralMilestoneCode = {
    AccountVerified: 'ACCOUNT_VERIFIED',
    FirstGeneration: 'FIRST_GENERATION',
    FirstPurchase: 'FIRST_PURCHASE'
} as const;
export type ReferralMilestoneCode = typeof ReferralMilestoneCode[keyof typeof ReferralMilestoneCode];


export function instanceOfReferralMilestoneCode(value: any): boolean {
    for (const key in ReferralMilestoneCode) {
        if (Object.prototype.hasOwnProperty.call(ReferralMilestoneCode, key)) {
            if (ReferralMilestoneCode[key as keyof typeof ReferralMilestoneCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReferralMilestoneCodeFromJSON(json: any): ReferralMilestoneCode {
    return ReferralMilestoneCodeFromJSONTyped(json, false);
}

export function ReferralMilestoneCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralMilestoneCode {
    return json as ReferralMilestoneCode;
}

export function ReferralMilestoneCodeToJSON(value?: ReferralMilestoneCode | null): any {
    return value as any;
}

export function ReferralMilestoneCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReferralMilestoneCode {
    return value as ReferralMilestoneCode;
}
