/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferralCampaign } from './ReferralCampaign';
import {
    ReferralCampaignFromJSON,
    ReferralCampaignFromJSONTyped,
    ReferralCampaignToJSON,
    ReferralCampaignToJSONTyped,
} from './ReferralCampaign';

/**
 *
 * @export
 * @interface ReferralCampaignListData
 */
export interface ReferralCampaignListData {
    /**
     *
     * @type {Array<ReferralCampaign>}
     * @memberof ReferralCampaignListData
     */
    items: Array<ReferralCampaign>;
    /**
     *
     * @type {string}
     * @memberof ReferralCampaignListData
     */
    nextCursor: string | null;
    /**
     *
     * @type {boolean}
     * @memberof ReferralCampaignListData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the ReferralCampaignListData interface.
 */
export function instanceOfReferralCampaignListData(value: object): value is ReferralCampaignListData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ReferralCampaignListDataFromJSON(json: any): ReferralCampaignListData {
    return ReferralCampaignListDataFromJSONTyped(json, false);
}

export function ReferralCampaignListDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralCampaignListData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ReferralCampaignFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function ReferralCampaignListDataToJSON(json: any): ReferralCampaignListData {
    return ReferralCampaignListDataToJSONTyped(json, false);
}

export function ReferralCampaignListDataToJSONTyped(value?: ReferralCampaignListData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ReferralCampaignToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
