/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferralMilestoneCode } from './ReferralMilestoneCode';
import {
    ReferralMilestoneCodeFromJSON,
    ReferralMilestoneCodeFromJSONTyped,
    ReferralMilestoneCodeToJSON,
    ReferralMilestoneCodeToJSONTyped,
} from './ReferralMilestoneCode';
import type { RewardUnit } from './RewardUnit';
import {
    RewardUnitFromJSON,
    RewardUnitFromJSONTyped,
    RewardUnitToJSON,
    RewardUnitToJSONTyped,
} from './RewardUnit';
import type { ReferralBeneficiary } from './ReferralBeneficiary';
import {
    ReferralBeneficiaryFromJSON,
    ReferralBeneficiaryFromJSONTyped,
    ReferralBeneficiaryToJSON,
    ReferralBeneficiaryToJSONTyped,
} from './ReferralBeneficiary';

/**
 *
 * @export
 * @interface ReferralRewardRule
 */
export interface ReferralRewardRule {
    /**
     *
     * @type {ReferralMilestoneCode}
     * @memberof ReferralRewardRule
     */
    milestoneCode: ReferralMilestoneCode;
    /**
     *
     * @type {ReferralBeneficiary}
     * @memberof ReferralRewardRule
     */
    beneficiary: ReferralBeneficiary;
    /**
     *
     * @type {RewardUnit}
     * @memberof ReferralRewardRule
     */
    rewardUnit: RewardUnit;
    /**
     *
     * @type {number}
     * @memberof ReferralRewardRule
     */
    rewardAmount: number;
    /**
     *
     * @type {number}
     * @memberof ReferralRewardRule
     */
    coolingOffHours: number;
}



/**
 * Check if a given object implements the ReferralRewardRule interface.
 */
export function instanceOfReferralRewardRule(value: object): value is ReferralRewardRule {
    if (!('milestoneCode' in value) || value['milestoneCode'] === undefined) return false;
    if (!('beneficiary' in value) || value['beneficiary'] === undefined) return false;
    if (!('rewardUnit' in value) || value['rewardUnit'] === undefined) return false;
    if (!('rewardAmount' in value) || value['rewardAmount'] === undefined) return false;
    if (!('coolingOffHours' in value) || value['coolingOffHours'] === undefined) return false;
    return true;
}

export function ReferralRewardRuleFromJSON(json: any): ReferralRewardRule {
    return ReferralRewardRuleFromJSONTyped(json, false);
}

export function ReferralRewardRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralRewardRule {
    if (json == null) {
        return json;
    }
    return {

        'milestoneCode': ReferralMilestoneCodeFromJSON(json['milestoneCode']),
        'beneficiary': ReferralBeneficiaryFromJSON(json['beneficiary']),
        'rewardUnit': RewardUnitFromJSON(json['rewardUnit']),
        'rewardAmount': json['rewardAmount'],
        'coolingOffHours': json['coolingOffHours'],
    };
}

export function ReferralRewardRuleToJSON(json: any): ReferralRewardRule {
    return ReferralRewardRuleToJSONTyped(json, false);
}

export function ReferralRewardRuleToJSONTyped(value?: ReferralRewardRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'milestoneCode': ReferralMilestoneCodeToJSON(value['milestoneCode']),
        'beneficiary': ReferralBeneficiaryToJSON(value['beneficiary']),
        'rewardUnit': RewardUnitToJSON(value['rewardUnit']),
        'rewardAmount': value['rewardAmount'],
        'coolingOffHours': value['coolingOffHours'],
    };
}
