/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const RefundStatus = {
    Requested: 'REQUESTED',
    Reviewing: 'REVIEWING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Processing: 'PROCESSING',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED'
} as const;
export type RefundStatus = typeof RefundStatus[keyof typeof RefundStatus];


export function instanceOfRefundStatus(value: any): boolean {
    for (const key in RefundStatus) {
        if (Object.prototype.hasOwnProperty.call(RefundStatus, key)) {
            if (RefundStatus[key as keyof typeof RefundStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RefundStatusFromJSON(json: any): RefundStatus {
    return RefundStatusFromJSONTyped(json, false);
}

export function RefundStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundStatus {
    return json as RefundStatus;
}

export function RefundStatusToJSON(value?: RefundStatus | null): any {
    return value as any;
}

export function RefundStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RefundStatus {
    return value as RefundStatus;
}
