/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RollbackProviderRequest
 */
export interface RollbackProviderRequest {
    /**
     *
     * @type {number}
     * @memberof RollbackProviderRequest
     */
    targetResourceVersion: number;
    /**
     *
     * @type {string}
     * @memberof RollbackProviderRequest
     */
    auditReason: string;
}

/**
 * Check if a given object implements the RollbackProviderRequest interface.
 */
export function instanceOfRollbackProviderRequest(value: object): value is RollbackProviderRequest {
    if (!('targetResourceVersion' in value) || value['targetResourceVersion'] === undefined) return false;
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    return true;
}

export function RollbackProviderRequestFromJSON(json: any): RollbackProviderRequest {
    return RollbackProviderRequestFromJSONTyped(json, false);
}

export function RollbackProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollbackProviderRequest {
    if (json == null) {
        return json;
    }
    return {

        'targetResourceVersion': json['targetResourceVersion'],
        'auditReason': json['auditReason'],
    };
}

export function RollbackProviderRequestToJSON(json: any): RollbackProviderRequest {
    return RollbackProviderRequestToJSONTyped(json, false);
}

export function RollbackProviderRequestToJSONTyped(value?: RollbackProviderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'targetResourceVersion': value['targetResourceVersion'],
        'auditReason': value['auditReason'],
    };
}
