/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SensitiveContentReadRequest
 */
export interface SensitiveContentReadRequest {
    /**
     *
     * @type {string}
     * @memberof SensitiveContentReadRequest
     */
    auditReason: string;
}

/**
 * Check if a given object implements the SensitiveContentReadRequest interface.
 */
export function instanceOfSensitiveContentReadRequest(value: object): value is SensitiveContentReadRequest {
    if (!('auditReason' in value) || value['auditReason'] === undefined) return false;
    return true;
}

export function SensitiveContentReadRequestFromJSON(json: any): SensitiveContentReadRequest {
    return SensitiveContentReadRequestFromJSONTyped(json, false);
}

export function SensitiveContentReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensitiveContentReadRequest {
    if (json == null) {
        return json;
    }
    return {

        'auditReason': json['auditReason'],
    };
}

export function SensitiveContentReadRequestToJSON(json: any): SensitiveContentReadRequest {
    return SensitiveContentReadRequestToJSONTyped(json, false);
}

export function SensitiveContentReadRequestToJSONTyped(value?: SensitiveContentReadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'auditReason': value['auditReason'],
    };
}
