/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SmsChallenge
 */
export interface SmsChallenge {
    /**
     *
     * @type {string}
     * @memberof SmsChallenge
     */
    challengeId: string;
    /**
     *
     * @type {Date}
     * @memberof SmsChallenge
     */
    expiresAt: Date;
    /**
     *
     * @type {number}
     * @memberof SmsChallenge
     */
    resendAfterSeconds: number;
}

/**
 * Check if a given object implements the SmsChallenge interface.
 */
export function instanceOfSmsChallenge(value: object): value is SmsChallenge {
    if (!('challengeId' in value) || value['challengeId'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('resendAfterSeconds' in value) || value['resendAfterSeconds'] === undefined) return false;
    return true;
}

export function SmsChallengeFromJSON(json: any): SmsChallenge {
    return SmsChallengeFromJSONTyped(json, false);
}

export function SmsChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsChallenge {
    if (json == null) {
        return json;
    }
    return {

        'challengeId': json['challengeId'],
        'expiresAt': (new Date(json['expiresAt'])),
        'resendAfterSeconds': json['resendAfterSeconds'],
    };
}

export function SmsChallengeToJSON(json: any): SmsChallenge {
    return SmsChallengeToJSONTyped(json, false);
}

export function SmsChallengeToJSONTyped(value?: SmsChallenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'challengeId': value['challengeId'],
        'expiresAt': value['expiresAt'].toISOString(),
        'resendAfterSeconds': value['resendAfterSeconds'],
    };
}
