/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionListData } from './SubscriptionListData';
import {
    SubscriptionListDataFromJSON,
    SubscriptionListDataFromJSONTyped,
    SubscriptionListDataToJSON,
    SubscriptionListDataToJSONTyped,
} from './SubscriptionListData';

/**
 *
 * @export
 * @interface SubscriptionListResponse
 */
export interface SubscriptionListResponse {
    /**
     *
     * @type {string}
     * @memberof SubscriptionListResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof SubscriptionListResponse
     */
    message: string;
    /**
     *
     * @type {SubscriptionListData}
     * @memberof SubscriptionListResponse
     */
    data: SubscriptionListData;
    /**
     *
     * @type {string}
     * @memberof SubscriptionListResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof SubscriptionListResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the SubscriptionListResponse interface.
 */
export function instanceOfSubscriptionListResponse(value: object): value is SubscriptionListResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function SubscriptionListResponseFromJSON(json: any): SubscriptionListResponse {
    return SubscriptionListResponseFromJSONTyped(json, false);
}

export function SubscriptionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionListResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': SubscriptionListDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function SubscriptionListResponseToJSON(json: any): SubscriptionListResponse {
    return SubscriptionListResponseToJSONTyped(json, false);
}

export function SubscriptionListResponseToJSONTyped(value?: SubscriptionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': SubscriptionListDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
