/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionStatus } from './SubscriptionStatus';
import {
    SubscriptionStatusFromJSON,
    SubscriptionStatusFromJSONTyped,
    SubscriptionStatusToJSON,
    SubscriptionStatusToJSONTyped,
} from './SubscriptionStatus';
import type { RenewalType } from './RenewalType';
import {
    RenewalTypeFromJSON,
    RenewalTypeFromJSONTyped,
    RenewalTypeToJSON,
    RenewalTypeToJSONTyped,
} from './RenewalType';

/**
 *
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     *
     * @type {string}
     * @memberof Subscription
     */
    subscriptionId: string;
    /**
     *
     * @type {string}
     * @memberof Subscription
     */
    productCode: string;
    /**
     *
     * @type {string}
     * @memberof Subscription
     */
    productVersionId: string;
    /**
     *
     * @type {SubscriptionStatus}
     * @memberof Subscription
     */
    status: SubscriptionStatus;
    /**
     *
     * @type {RenewalType}
     * @memberof Subscription
     */
    renewalType: RenewalType;
    /**
     *
     * @type {Date}
     * @memberof Subscription
     */
    currentPeriodStartsAt: Date;
    /**
     *
     * @type {Date}
     * @memberof Subscription
     */
    currentPeriodEndsAt: Date;
    /**
     *
     * @type {boolean}
     * @memberof Subscription
     */
    autoRenew: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Subscription
     */
    cancelAtPeriodEnd?: boolean;
    /**
     *
     * @type {number}
     * @memberof Subscription
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof Subscription
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof Subscription
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('productCode' in value) || value['productCode'] === undefined) return false;
    if (!('productVersionId' in value) || value['productVersionId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('renewalType' in value) || value['renewalType'] === undefined) return false;
    if (!('currentPeriodStartsAt' in value) || value['currentPeriodStartsAt'] === undefined) return false;
    if (!('currentPeriodEndsAt' in value) || value['currentPeriodEndsAt'] === undefined) return false;
    if (!('autoRenew' in value) || value['autoRenew'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {

        'subscriptionId': json['subscriptionId'],
        'productCode': json['productCode'],
        'productVersionId': json['productVersionId'],
        'status': SubscriptionStatusFromJSON(json['status']),
        'renewalType': RenewalTypeFromJSON(json['renewalType']),
        'currentPeriodStartsAt': (new Date(json['currentPeriodStartsAt'])),
        'currentPeriodEndsAt': (new Date(json['currentPeriodEndsAt'])),
        'autoRenew': json['autoRenew'],
        'cancelAtPeriodEnd': json['cancelAtPeriodEnd'] == null ? undefined : json['cancelAtPeriodEnd'],
        'resourceVersion': json['resourceVersion'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function SubscriptionToJSON(json: any): Subscription {
    return SubscriptionToJSONTyped(json, false);
}

export function SubscriptionToJSONTyped(value?: Subscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'subscriptionId': value['subscriptionId'],
        'productCode': value['productCode'],
        'productVersionId': value['productVersionId'],
        'status': SubscriptionStatusToJSON(value['status']),
        'renewalType': RenewalTypeToJSON(value['renewalType']),
        'currentPeriodStartsAt': value['currentPeriodStartsAt'].toISOString(),
        'currentPeriodEndsAt': value['currentPeriodEndsAt'].toISOString(),
        'autoRenew': value['autoRenew'],
        'cancelAtPeriodEnd': value['cancelAtPeriodEnd'],
        'resourceVersion': value['resourceVersion'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
