/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupportTicket } from './SupportTicket';
import {
    SupportTicketFromJSON,
    SupportTicketFromJSONTyped,
    SupportTicketToJSON,
    SupportTicketToJSONTyped,
} from './SupportTicket';

/**
 *
 * @export
 * @interface SupportTicketResponse
 */
export interface SupportTicketResponse {
    /**
     *
     * @type {string}
     * @memberof SupportTicketResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof SupportTicketResponse
     */
    message: string;
    /**
     *
     * @type {SupportTicket}
     * @memberof SupportTicketResponse
     */
    data: SupportTicket;
    /**
     *
     * @type {string}
     * @memberof SupportTicketResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof SupportTicketResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the SupportTicketResponse interface.
 */
export function instanceOfSupportTicketResponse(value: object): value is SupportTicketResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function SupportTicketResponseFromJSON(json: any): SupportTicketResponse {
    return SupportTicketResponseFromJSONTyped(json, false);
}

export function SupportTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportTicketResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': SupportTicketFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function SupportTicketResponseToJSON(json: any): SupportTicketResponse {
    return SupportTicketResponseToJSONTyped(json, false);
}

export function SupportTicketResponseToJSONTyped(value?: SupportTicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': SupportTicketToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
