/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TokenPair
 */
export interface TokenPair {
    /**
     *
     * @type {string}
     * @memberof TokenPair
     */
    accessToken: string;
    /**
     *
     * @type {Date}
     * @memberof TokenPair
     */
    accessTokenExpiresAt: Date;
    /**
     *
     * @type {string}
     * @memberof TokenPair
     */
    refreshToken: string;
    /**
     *
     * @type {Date}
     * @memberof TokenPair
     */
    refreshTokenExpiresAt: Date;
}

/**
 * Check if a given object implements the TokenPair interface.
 */
export function instanceOfTokenPair(value: object): value is TokenPair {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('accessTokenExpiresAt' in value) || value['accessTokenExpiresAt'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('refreshTokenExpiresAt' in value) || value['refreshTokenExpiresAt'] === undefined) return false;
    return true;
}

export function TokenPairFromJSON(json: any): TokenPair {
    return TokenPairFromJSONTyped(json, false);
}

export function TokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPair {
    if (json == null) {
        return json;
    }
    return {

        'accessToken': json['accessToken'],
        'accessTokenExpiresAt': (new Date(json['accessTokenExpiresAt'])),
        'refreshToken': json['refreshToken'],
        'refreshTokenExpiresAt': (new Date(json['refreshTokenExpiresAt'])),
    };
}

export function TokenPairToJSON(json: any): TokenPair {
    return TokenPairToJSONTyped(json, false);
}

export function TokenPairToJSONTyped(value?: TokenPair | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'accessToken': value['accessToken'],
        'accessTokenExpiresAt': value['accessTokenExpiresAt'].toISOString(),
        'refreshToken': value['refreshToken'],
        'refreshTokenExpiresAt': value['refreshTokenExpiresAt'].toISOString(),
    };
}
