/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateConsentRequest
 */
export interface UpdateConsentRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateConsentRequest
     */
    documentVersion: string;
    /**
     *
     * @type {boolean}
     * @memberof UpdateConsentRequest
     */
    granted: boolean;
}

/**
 * Check if a given object implements the UpdateConsentRequest interface.
 */
export function instanceOfUpdateConsentRequest(value: object): value is UpdateConsentRequest {
    if (!('documentVersion' in value) || value['documentVersion'] === undefined) return false;
    if (!('granted' in value) || value['granted'] === undefined) return false;
    return true;
}

export function UpdateConsentRequestFromJSON(json: any): UpdateConsentRequest {
    return UpdateConsentRequestFromJSONTyped(json, false);
}

export function UpdateConsentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConsentRequest {
    if (json == null) {
        return json;
    }
    return {

        'documentVersion': json['documentVersion'],
        'granted': json['granted'],
    };
}

export function UpdateConsentRequestToJSON(json: any): UpdateConsentRequest {
    return UpdateConsentRequestToJSONTyped(json, false);
}

export function UpdateConsentRequestToJSONTyped(value?: UpdateConsentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'documentVersion': value['documentVersion'],
        'granted': value['granted'],
    };
}
