/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountStatus } from './AccountStatus';
import {
    AccountStatusFromJSON,
    AccountStatusFromJSONTyped,
    AccountStatusToJSON,
    AccountStatusToJSONTyped,
} from './AccountStatus';

/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {string}
     * @memberof User
     */
    userId: string;
    /**
     *
     * @type {AccountStatus}
     * @memberof User
     */
    status: AccountStatus;
    /**
     *
     * @type {string}
     * @memberof User
     */
    nickname?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    avatarUrl?: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    locale: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    timeZone: string;
    /**
     *
     * @type {number}
     * @memberof User
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('locale' in value) || value['locale'] === undefined) return false;
    if (!('timeZone' in value) || value['timeZone'] === undefined) return false;
    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {

        'userId': json['userId'],
        'status': AccountStatusFromJSON(json['status']),
        'nickname': json['nickname'] === undefined ? undefined : json['nickname'] === null ? null : json['nickname'],
        'avatarUrl': json['avatarUrl'] === undefined ? undefined : json['avatarUrl'] === null ? null : json['avatarUrl'],
        'locale': json['locale'],
        'timeZone': json['timeZone'],
        'resourceVersion': json['resourceVersion'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'userId': value['userId'],
        'status': AccountStatusToJSON(value['status']),
        'nickname': value['nickname'],
        'avatarUrl': value['avatarUrl'],
        'locale': value['locale'],
        'timeZone': value['timeZone'],
        'resourceVersion': value['resourceVersion'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
