/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletLedgerEntry } from './WalletLedgerEntry';
import {
    WalletLedgerEntryFromJSON,
    WalletLedgerEntryFromJSONTyped,
    WalletLedgerEntryToJSON,
    WalletLedgerEntryToJSONTyped,
} from './WalletLedgerEntry';

/**
 *
 * @export
 * @interface WalletLedgerData
 */
export interface WalletLedgerData {
    /**
     *
     * @type {Array<WalletLedgerEntry>}
     * @memberof WalletLedgerData
     */
    items: Array<WalletLedgerEntry>;
    /**
     *
     * @type {string}
     * @memberof WalletLedgerData
     */
    nextCursor: string | null;
    /**
     *
     * @type {boolean}
     * @memberof WalletLedgerData
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the WalletLedgerData interface.
 */
export function instanceOfWalletLedgerData(value: object): value is WalletLedgerData {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function WalletLedgerDataFromJSON(json: any): WalletLedgerData {
    return WalletLedgerDataFromJSONTyped(json, false);
}

export function WalletLedgerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletLedgerData {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(WalletLedgerEntryFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function WalletLedgerDataToJSON(json: any): WalletLedgerData {
    return WalletLedgerDataToJSONTyped(json, false);
}

export function WalletLedgerDataToJSONTyped(value?: WalletLedgerData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(WalletLedgerEntryToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}
