/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletLedgerData } from './WalletLedgerData';
import {
    WalletLedgerDataFromJSON,
    WalletLedgerDataFromJSONTyped,
    WalletLedgerDataToJSON,
    WalletLedgerDataToJSONTyped,
} from './WalletLedgerData';

/**
 *
 * @export
 * @interface WalletLedgerResponse
 */
export interface WalletLedgerResponse {
    /**
     *
     * @type {string}
     * @memberof WalletLedgerResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof WalletLedgerResponse
     */
    message: string;
    /**
     *
     * @type {WalletLedgerData}
     * @memberof WalletLedgerResponse
     */
    data: WalletLedgerData;
    /**
     *
     * @type {string}
     * @memberof WalletLedgerResponse
     */
    requestId: string;
    /**
     *
     * @type {Date}
     * @memberof WalletLedgerResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the WalletLedgerResponse interface.
 */
export function instanceOfWalletLedgerResponse(value: object): value is WalletLedgerResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function WalletLedgerResponseFromJSON(json: any): WalletLedgerResponse {
    return WalletLedgerResponseFromJSONTyped(json, false);
}

export function WalletLedgerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletLedgerResponse {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'message': json['message'],
        'data': WalletLedgerDataFromJSON(json['data']),
        'requestId': json['requestId'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function WalletLedgerResponseToJSON(json: any): WalletLedgerResponse {
    return WalletLedgerResponseToJSONTyped(json, false);
}

export function WalletLedgerResponseToJSONTyped(value?: WalletLedgerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'message': value['message'],
        'data': WalletLedgerDataToJSON(value['data']),
        'requestId': value['requestId'],
        'timestamp': value['timestamp'].toISOString(),
    };
}
