/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     *
     * @type {number}
     * @memberof Wallet
     */
    energyBalance: number;
    /**
     *
     * @type {number}
     * @memberof Wallet
     */
    energyReserved: number;
    /**
     *
     * @type {number}
     * @memberof Wallet
     */
    energyAvailable: number;
    /**
     *
     * @type {WalletCurrencyEnum}
     * @memberof Wallet
     */
    currency: WalletCurrencyEnum;
    /**
     *
     * @type {number}
     * @memberof Wallet
     */
    resourceVersion: number;
    /**
     *
     * @type {Date}
     * @memberof Wallet
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const WalletCurrencyEnum = {
    Energy: 'ENERGY'
} as const;
export type WalletCurrencyEnum = typeof WalletCurrencyEnum[keyof typeof WalletCurrencyEnum];


/**
 * Check if a given object implements the Wallet interface.
 */
export function instanceOfWallet(value: object): value is Wallet {
    if (!('energyBalance' in value) || value['energyBalance'] === undefined) return false;
    if (!('energyReserved' in value) || value['energyReserved'] === undefined) return false;
    if (!('energyAvailable' in value) || value['energyAvailable'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (value['currency'] !== 'ENERGY') return false;

    if (!('resourceVersion' in value) || value['resourceVersion'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WalletFromJSON(json: any): Wallet {
    return WalletFromJSONTyped(json, false);
}

export function WalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallet {
    if (json == null) {
        return json;
    }
    return {

        'energyBalance': json['energyBalance'],
        'energyReserved': json['energyReserved'],
        'energyAvailable': json['energyAvailable'],
        'currency': json['currency'],
        'resourceVersion': json['resourceVersion'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function WalletToJSON(json: any): Wallet {
    return WalletToJSONTyped(json, false);
}

export function WalletToJSONTyped(value?: Wallet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'energyBalance': value['energyBalance'],
        'energyReserved': value['energyReserved'],
        'energyAvailable': value['energyAvailable'],
        'currency': value['currency'],
        'resourceVersion': value['resourceVersion'],
        'updatedAt': value['updatedAt'].toISOString(),
    };
}
