/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminOrderListResponse,
    AdminOrderListResponseFromJSON,
    AdminOrderListResponseToJSON,
} from '../models/AdminOrderListResponse';
import {
    type AdminOrderResponse,
    AdminOrderResponseFromJSON,
    AdminOrderResponseToJSON,
} from '../models/AdminOrderResponse';
import {
    type AdminProductListResponse,
    AdminProductListResponseFromJSON,
    AdminProductListResponseToJSON,
} from '../models/AdminProductListResponse';
import {
    type AdminProductPublishRequest,
    AdminProductPublishRequestFromJSON,
    AdminProductPublishRequestToJSON,
} from '../models/AdminProductPublishRequest';
import {
    type AdminProductResponse,
    AdminProductResponseFromJSON,
    AdminProductResponseToJSON,
} from '../models/AdminProductResponse';
import {
    type AdminProductRollbackRequest,
    AdminProductRollbackRequestFromJSON,
    AdminProductRollbackRequestToJSON,
} from '../models/AdminProductRollbackRequest';
import {
    type AdminProductWriteRequest,
    AdminProductWriteRequestFromJSON,
    AdminProductWriteRequestToJSON,
} from '../models/AdminProductWriteRequest';
import {
    type AdminRefundDecisionRequest,
    AdminRefundDecisionRequestFromJSON,
    AdminRefundDecisionRequestToJSON,
} from '../models/AdminRefundDecisionRequest';
import {
    type AdminRefundExecuteRequest,
    AdminRefundExecuteRequestFromJSON,
    AdminRefundExecuteRequestToJSON,
} from '../models/AdminRefundExecuteRequest';
import {
    type AdminRefundListResponse,
    AdminRefundListResponseFromJSON,
    AdminRefundListResponseToJSON,
} from '../models/AdminRefundListResponse';
import {
    type AdminRefundResponse,
    AdminRefundResponseFromJSON,
    AdminRefundResponseToJSON,
} from '../models/AdminRefundResponse';
import {
    type EntitlementAdjustmentRequest,
    EntitlementAdjustmentRequestFromJSON,
    EntitlementAdjustmentRequestToJSON,
} from '../models/EntitlementAdjustmentRequest';
import {
    type EntitlementAdjustmentResponse,
    EntitlementAdjustmentResponseFromJSON,
    EntitlementAdjustmentResponseToJSON,
} from '../models/EntitlementAdjustmentResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type PaymentReconciliationRequest,
    PaymentReconciliationRequestFromJSON,
    PaymentReconciliationRequestToJSON,
} from '../models/PaymentReconciliationRequest';
import {
    type PaymentReconciliationResponse,
    PaymentReconciliationResponseFromJSON,
    PaymentReconciliationResponseToJSON,
} from '../models/PaymentReconciliationResponse';

export interface CreateAdminEntitlementAdjustmentRequest {
    xClientVersion: string;
    xPlatform: CreateAdminEntitlementAdjustmentXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    entitlementAdjustmentRequest: EntitlementAdjustmentRequest;
    xRequestId?: string;
}

export interface CreateAdminProductRequest {
    xClientVersion: string;
    xPlatform: CreateAdminProductXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    adminProductWriteRequest: AdminProductWriteRequest;
    xRequestId?: string;
}

export interface DecideAdminRefundRequest {
    refundId: string;
    xClientVersion: string;
    xPlatform: DecideAdminRefundXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    ifMatch: string;
    adminRefundDecisionRequest: AdminRefundDecisionRequest;
    xRequestId?: string;
}

export interface ExecuteAdminRefundRequest {
    refundId: string;
    xClientVersion: string;
    xPlatform: ExecuteAdminRefundXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    ifMatch: string;
    adminRefundExecuteRequest: AdminRefundExecuteRequest;
    xRequestId?: string;
}

export interface GetAdminOrderRequest {
    orderId: string;
    xClientVersion: string;
    xPlatform: GetAdminOrderXPlatformEnum;
    acceptLanguage: string;
    xRequestId?: string;
}

export interface GetAdminProductRequest {
    productVersionId: string;
    xClientVersion: string;
    xPlatform: GetAdminProductXPlatformEnum;
    acceptLanguage: string;
    xRequestId?: string;
}

export interface GetAdminRefundRequest {
    refundId: string;
    xClientVersion: string;
    xPlatform: GetAdminRefundXPlatformEnum;
    acceptLanguage: string;
    xRequestId?: string;
}

export interface ListAdminOrdersRequest {
    xClientVersion: string;
    xPlatform: ListAdminOrdersXPlatformEnum;
    acceptLanguage: string;
    xRequestId?: string;
    cursor?: string | null;
    limit?: number;
}

export interface ListAdminProductsRequest {
    xClientVersion: string;
    xPlatform: ListAdminProductsXPlatformEnum;
    acceptLanguage: string;
    xRequestId?: string;
    cursor?: string | null;
    limit?: number;
}

export interface ListAdminRefundsRequest {
    xClientVersion: string;
    xPlatform: ListAdminRefundsXPlatformEnum;
    acceptLanguage: string;
    xRequestId?: string;
    cursor?: string | null;
    limit?: number;
}

export interface PublishAdminProductRequest {
    productVersionId: string;
    xClientVersion: string;
    xPlatform: PublishAdminProductXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    ifMatch: string;
    adminProductPublishRequest: AdminProductPublishRequest;
    xRequestId?: string;
}

export interface RollbackAdminProductRequest {
    productCode: string;
    xClientVersion: string;
    xPlatform: RollbackAdminProductXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    adminProductRollbackRequest: AdminProductRollbackRequest;
    xRequestId?: string;
}

export interface RunAdminPaymentReconciliationRequest {
    xClientVersion: string;
    xPlatform: RunAdminPaymentReconciliationXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    paymentReconciliationRequest: PaymentReconciliationRequest;
    xRequestId?: string;
}

export interface UpdateAdminProductRequest {
    productVersionId: string;
    xClientVersion: string;
    xPlatform: UpdateAdminProductXPlatformEnum;
    acceptLanguage: string;
    idempotencyKey: string;
    ifMatch: string;
    adminProductWriteRequest: AdminProductWriteRequest;
    xRequestId?: string;
}

/**
 * ADMINCOMMERCEApi - interface
 *
 * @export
 * @interface ADMINCOMMERCEApiInterface
 */
export interface ADMINCOMMERCEApiInterface {
    /**
     * Creates request options for createAdminEntitlementAdjustment without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {EntitlementAdjustmentRequest} entitlementAdjustmentRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    createAdminEntitlementAdjustmentRequestOpts(requestParameters: CreateAdminEntitlementAdjustmentRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Apply one idempotent and audited manual benefit adjustment
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {EntitlementAdjustmentRequest} entitlementAdjustmentRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    createAdminEntitlementAdjustmentRaw(requestParameters: CreateAdminEntitlementAdjustmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitlementAdjustmentResponse>>;

    /**
     * Apply one idempotent and audited manual benefit adjustment
     */
    createAdminEntitlementAdjustment(requestParameters: CreateAdminEntitlementAdjustmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitlementAdjustmentResponse>;

    /**
     * Creates request options for createAdminProduct without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {AdminProductWriteRequest} adminProductWriteRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    createAdminProductRequestOpts(requestParameters: CreateAdminProductRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Create a new immutable product draft version
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {AdminProductWriteRequest} adminProductWriteRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    createAdminProductRaw(requestParameters: CreateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>>;

    /**
     * Create a new immutable product draft version
     */
    createAdminProduct(requestParameters: CreateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse>;

    /**
     * Creates request options for decideAdminRefund without sending the request
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminRefundDecisionRequest} adminRefundDecisionRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    decideAdminRefundRequestOpts(requestParameters: DecideAdminRefundRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Approve or reject a refund request
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminRefundDecisionRequest} adminRefundDecisionRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    decideAdminRefundRaw(requestParameters: DecideAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundResponse>>;

    /**
     * Approve or reject a refund request
     */
    decideAdminRefund(requestParameters: DecideAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundResponse>;

    /**
     * Creates request options for executeAdminRefund without sending the request
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminRefundExecuteRequest} adminRefundExecuteRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    executeAdminRefundRequestOpts(requestParameters: ExecuteAdminRefundRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Execute an approved provider refund and recover eligible benefits
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminRefundExecuteRequest} adminRefundExecuteRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    executeAdminRefundRaw(requestParameters: ExecuteAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundResponse>>;

    /**
     * Execute an approved provider refund and recover eligible benefits
     */
    executeAdminRefund(requestParameters: ExecuteAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundResponse>;

    /**
     * Creates request options for getAdminOrder without sending the request
     * @param {string} orderId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    getAdminOrderRequestOpts(requestParameters: GetAdminOrderRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Read one order and all payment attempts
     * @param {string} orderId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    getAdminOrderRaw(requestParameters: GetAdminOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrderResponse>>;

    /**
     * Read one order and all payment attempts
     */
    getAdminOrder(requestParameters: GetAdminOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrderResponse>;

    /**
     * Creates request options for getAdminProduct without sending the request
     * @param {string} productVersionId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    getAdminProductRequestOpts(requestParameters: GetAdminProductRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Read one product version
     * @param {string} productVersionId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    getAdminProductRaw(requestParameters: GetAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>>;

    /**
     * Read one product version
     */
    getAdminProduct(requestParameters: GetAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse>;

    /**
     * Creates request options for getAdminRefund without sending the request
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    getAdminRefundRequestOpts(requestParameters: GetAdminRefundRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Read one refund request
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    getAdminRefundRaw(requestParameters: GetAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundResponse>>;

    /**
     * Read one refund request
     */
    getAdminRefund(requestParameters: GetAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundResponse>;

    /**
     * Creates request options for listAdminOrders without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {string} [cursor] Opaque server-issued cursor. Clients must not parse it.
     * @param {number} [limit]
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    listAdminOrdersRequestOpts(requestParameters: ListAdminOrdersRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary List immutable order and payment facts
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {string} [cursor] Opaque server-issued cursor. Clients must not parse it.
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    listAdminOrdersRaw(requestParameters: ListAdminOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrderListResponse>>;

    /**
     * List immutable order and payment facts
     */
    listAdminOrders(requestParameters: ListAdminOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrderListResponse>;

    /**
     * Creates request options for listAdminProducts without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {string} [cursor] Opaque server-issued cursor. Clients must not parse it.
     * @param {number} [limit]
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    listAdminProductsRequestOpts(requestParameters: ListAdminProductsRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary List all product drafts and published versions
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {string} [cursor] Opaque server-issued cursor. Clients must not parse it.
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    listAdminProductsRaw(requestParameters: ListAdminProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductListResponse>>;

    /**
     * List all product drafts and published versions
     */
    listAdminProducts(requestParameters: ListAdminProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductListResponse>;

    /**
     * Creates request options for listAdminRefunds without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {string} [cursor] Opaque server-issued cursor. Clients must not parse it.
     * @param {number} [limit]
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    listAdminRefundsRequestOpts(requestParameters: ListAdminRefundsRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary List refund requests and recovery status
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {string} [cursor] Opaque server-issued cursor. Clients must not parse it.
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    listAdminRefundsRaw(requestParameters: ListAdminRefundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundListResponse>>;

    /**
     * List refund requests and recovery status
     */
    listAdminRefunds(requestParameters: ListAdminRefundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundListResponse>;

    /**
     * Creates request options for publishAdminProduct without sending the request
     * @param {string} productVersionId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminProductPublishRequest} adminProductPublishRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    publishAdminProductRequestOpts(requestParameters: PublishAdminProductRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Publish a product version with maker-checker approval
     * @param {string} productVersionId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminProductPublishRequest} adminProductPublishRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    publishAdminProductRaw(requestParameters: PublishAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>>;

    /**
     * Publish a product version with maker-checker approval
     */
    publishAdminProduct(requestParameters: PublishAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse>;

    /**
     * Creates request options for rollbackAdminProduct without sending the request
     * @param {string} productCode
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {AdminProductRollbackRequest} adminProductRollbackRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    rollbackAdminProductRequestOpts(requestParameters: RollbackAdminProductRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Re-publish a previously published immutable version
     * @param {string} productCode
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {AdminProductRollbackRequest} adminProductRollbackRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    rollbackAdminProductRaw(requestParameters: RollbackAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>>;

    /**
     * Re-publish a previously published immutable version
     */
    rollbackAdminProduct(requestParameters: RollbackAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse>;

    /**
     * Creates request options for runAdminPaymentReconciliation without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {PaymentReconciliationRequest} paymentReconciliationRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    runAdminPaymentReconciliationRequestOpts(requestParameters: RunAdminPaymentReconciliationRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Reconcile stale payment attempts and recover interrupted grants
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {PaymentReconciliationRequest} paymentReconciliationRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    runAdminPaymentReconciliationRaw(requestParameters: RunAdminPaymentReconciliationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentReconciliationResponse>>;

    /**
     * Reconcile stale payment attempts and recover interrupted grants
     */
    runAdminPaymentReconciliation(requestParameters: RunAdminPaymentReconciliationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentReconciliationResponse>;

    /**
     * Creates request options for updateAdminProduct without sending the request
     * @param {string} productVersionId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminProductWriteRequest} adminProductWriteRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    updateAdminProductRequestOpts(requestParameters: UpdateAdminProductRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Replace a draft with a new immutable product version
     * @param {string} productVersionId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} ifMatch Decimal resourceVersion expected by the caller.
     * @param {AdminProductWriteRequest} adminProductWriteRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ADMINCOMMERCEApiInterface
     */
    updateAdminProductRaw(requestParameters: UpdateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>>;

    /**
     * Replace a draft with a new immutable product version
     */
    updateAdminProduct(requestParameters: UpdateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse>;

}

/**
 *
 */
export class ADMINCOMMERCEApi extends runtime.BaseAPI implements ADMINCOMMERCEApiInterface {

    /**
     * Creates request options for createAdminEntitlementAdjustment without sending the request
     */
    async createAdminEntitlementAdjustmentRequestOpts(requestParameters: CreateAdminEntitlementAdjustmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling createAdminEntitlementAdjustment().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling createAdminEntitlementAdjustment().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling createAdminEntitlementAdjustment().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createAdminEntitlementAdjustment().'
            );
        }

        if (requestParameters['entitlementAdjustmentRequest'] == null) {
            throw new runtime.RequiredError(
                'entitlementAdjustmentRequest',
                'Required parameter "entitlementAdjustmentRequest" was null or undefined when calling createAdminEntitlementAdjustment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/entitlement-adjustments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EntitlementAdjustmentRequestToJSON(requestParameters['entitlementAdjustmentRequest']),
        };
    }

    /**
     * Apply one idempotent and audited manual benefit adjustment
     */
    async createAdminEntitlementAdjustmentRaw(requestParameters: CreateAdminEntitlementAdjustmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntitlementAdjustmentResponse>> {
        const requestOptions = await this.createAdminEntitlementAdjustmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntitlementAdjustmentResponseFromJSON(jsonValue));
    }

    /**
     * Apply one idempotent and audited manual benefit adjustment
     */
    async createAdminEntitlementAdjustment(requestParameters: CreateAdminEntitlementAdjustmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntitlementAdjustmentResponse> {
        const response = await this.createAdminEntitlementAdjustmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAdminProduct without sending the request
     */
    async createAdminProductRequestOpts(requestParameters: CreateAdminProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling createAdminProduct().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling createAdminProduct().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling createAdminProduct().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createAdminProduct().'
            );
        }

        if (requestParameters['adminProductWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'adminProductWriteRequest',
                'Required parameter "adminProductWriteRequest" was null or undefined when calling createAdminProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/products`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminProductWriteRequestToJSON(requestParameters['adminProductWriteRequest']),
        };
    }

    /**
     * Create a new immutable product draft version
     */
    async createAdminProductRaw(requestParameters: CreateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>> {
        const requestOptions = await this.createAdminProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminProductResponseFromJSON(jsonValue));
    }

    /**
     * Create a new immutable product draft version
     */
    async createAdminProduct(requestParameters: CreateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse> {
        const response = await this.createAdminProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for decideAdminRefund without sending the request
     */
    async decideAdminRefundRequestOpts(requestParameters: DecideAdminRefundRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refundId'] == null) {
            throw new runtime.RequiredError(
                'refundId',
                'Required parameter "refundId" was null or undefined when calling decideAdminRefund().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling decideAdminRefund().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling decideAdminRefund().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling decideAdminRefund().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling decideAdminRefund().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling decideAdminRefund().'
            );
        }

        if (requestParameters['adminRefundDecisionRequest'] == null) {
            throw new runtime.RequiredError(
                'adminRefundDecisionRequest',
                'Required parameter "adminRefundDecisionRequest" was null or undefined when calling decideAdminRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/refunds/{refundId}/decision`;
        urlPath = urlPath.replace('{refundId}', encodeURIComponent(String(requestParameters['refundId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminRefundDecisionRequestToJSON(requestParameters['adminRefundDecisionRequest']),
        };
    }

    /**
     * Approve or reject a refund request
     */
    async decideAdminRefundRaw(requestParameters: DecideAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundResponse>> {
        const requestOptions = await this.decideAdminRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminRefundResponseFromJSON(jsonValue));
    }

    /**
     * Approve or reject a refund request
     */
    async decideAdminRefund(requestParameters: DecideAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundResponse> {
        const response = await this.decideAdminRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for executeAdminRefund without sending the request
     */
    async executeAdminRefundRequestOpts(requestParameters: ExecuteAdminRefundRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refundId'] == null) {
            throw new runtime.RequiredError(
                'refundId',
                'Required parameter "refundId" was null or undefined when calling executeAdminRefund().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling executeAdminRefund().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling executeAdminRefund().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling executeAdminRefund().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling executeAdminRefund().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling executeAdminRefund().'
            );
        }

        if (requestParameters['adminRefundExecuteRequest'] == null) {
            throw new runtime.RequiredError(
                'adminRefundExecuteRequest',
                'Required parameter "adminRefundExecuteRequest" was null or undefined when calling executeAdminRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/refunds/{refundId}/execute`;
        urlPath = urlPath.replace('{refundId}', encodeURIComponent(String(requestParameters['refundId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminRefundExecuteRequestToJSON(requestParameters['adminRefundExecuteRequest']),
        };
    }

    /**
     * Execute an approved provider refund and recover eligible benefits
     */
    async executeAdminRefundRaw(requestParameters: ExecuteAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundResponse>> {
        const requestOptions = await this.executeAdminRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminRefundResponseFromJSON(jsonValue));
    }

    /**
     * Execute an approved provider refund and recover eligible benefits
     */
    async executeAdminRefund(requestParameters: ExecuteAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundResponse> {
        const response = await this.executeAdminRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAdminOrder without sending the request
     */
    async getAdminOrderRequestOpts(requestParameters: GetAdminOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getAdminOrder().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling getAdminOrder().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling getAdminOrder().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling getAdminOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/orders/{orderId}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read one order and all payment attempts
     */
    async getAdminOrderRaw(requestParameters: GetAdminOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrderResponse>> {
        const requestOptions = await this.getAdminOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrderResponseFromJSON(jsonValue));
    }

    /**
     * Read one order and all payment attempts
     */
    async getAdminOrder(requestParameters: GetAdminOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrderResponse> {
        const response = await this.getAdminOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAdminProduct without sending the request
     */
    async getAdminProductRequestOpts(requestParameters: GetAdminProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productVersionId'] == null) {
            throw new runtime.RequiredError(
                'productVersionId',
                'Required parameter "productVersionId" was null or undefined when calling getAdminProduct().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling getAdminProduct().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling getAdminProduct().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling getAdminProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/products/{productVersionId}`;
        urlPath = urlPath.replace('{productVersionId}', encodeURIComponent(String(requestParameters['productVersionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read one product version
     */
    async getAdminProductRaw(requestParameters: GetAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>> {
        const requestOptions = await this.getAdminProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminProductResponseFromJSON(jsonValue));
    }

    /**
     * Read one product version
     */
    async getAdminProduct(requestParameters: GetAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse> {
        const response = await this.getAdminProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAdminRefund without sending the request
     */
    async getAdminRefundRequestOpts(requestParameters: GetAdminRefundRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refundId'] == null) {
            throw new runtime.RequiredError(
                'refundId',
                'Required parameter "refundId" was null or undefined when calling getAdminRefund().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling getAdminRefund().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling getAdminRefund().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling getAdminRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/refunds/{refundId}`;
        urlPath = urlPath.replace('{refundId}', encodeURIComponent(String(requestParameters['refundId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read one refund request
     */
    async getAdminRefundRaw(requestParameters: GetAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundResponse>> {
        const requestOptions = await this.getAdminRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminRefundResponseFromJSON(jsonValue));
    }

    /**
     * Read one refund request
     */
    async getAdminRefund(requestParameters: GetAdminRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundResponse> {
        const response = await this.getAdminRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminOrders without sending the request
     */
    async listAdminOrdersRequestOpts(requestParameters: ListAdminOrdersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling listAdminOrders().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling listAdminOrders().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling listAdminOrders().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List immutable order and payment facts
     */
    async listAdminOrdersRaw(requestParameters: ListAdminOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminOrderListResponse>> {
        const requestOptions = await this.listAdminOrdersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminOrderListResponseFromJSON(jsonValue));
    }

    /**
     * List immutable order and payment facts
     */
    async listAdminOrders(requestParameters: ListAdminOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminOrderListResponse> {
        const response = await this.listAdminOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminProducts without sending the request
     */
    async listAdminProductsRequestOpts(requestParameters: ListAdminProductsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling listAdminProducts().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling listAdminProducts().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling listAdminProducts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all product drafts and published versions
     */
    async listAdminProductsRaw(requestParameters: ListAdminProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductListResponse>> {
        const requestOptions = await this.listAdminProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminProductListResponseFromJSON(jsonValue));
    }

    /**
     * List all product drafts and published versions
     */
    async listAdminProducts(requestParameters: ListAdminProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductListResponse> {
        const response = await this.listAdminProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminRefunds without sending the request
     */
    async listAdminRefundsRequestOpts(requestParameters: ListAdminRefundsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling listAdminRefunds().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling listAdminRefunds().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling listAdminRefunds().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/refunds`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List refund requests and recovery status
     */
    async listAdminRefundsRaw(requestParameters: ListAdminRefundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminRefundListResponse>> {
        const requestOptions = await this.listAdminRefundsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminRefundListResponseFromJSON(jsonValue));
    }

    /**
     * List refund requests and recovery status
     */
    async listAdminRefunds(requestParameters: ListAdminRefundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminRefundListResponse> {
        const response = await this.listAdminRefundsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishAdminProduct without sending the request
     */
    async publishAdminProductRequestOpts(requestParameters: PublishAdminProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productVersionId'] == null) {
            throw new runtime.RequiredError(
                'productVersionId',
                'Required parameter "productVersionId" was null or undefined when calling publishAdminProduct().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling publishAdminProduct().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling publishAdminProduct().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling publishAdminProduct().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling publishAdminProduct().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling publishAdminProduct().'
            );
        }

        if (requestParameters['adminProductPublishRequest'] == null) {
            throw new runtime.RequiredError(
                'adminProductPublishRequest',
                'Required parameter "adminProductPublishRequest" was null or undefined when calling publishAdminProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/products/{productVersionId}/publish`;
        urlPath = urlPath.replace('{productVersionId}', encodeURIComponent(String(requestParameters['productVersionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminProductPublishRequestToJSON(requestParameters['adminProductPublishRequest']),
        };
    }

    /**
     * Publish a product version with maker-checker approval
     */
    async publishAdminProductRaw(requestParameters: PublishAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>> {
        const requestOptions = await this.publishAdminProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminProductResponseFromJSON(jsonValue));
    }

    /**
     * Publish a product version with maker-checker approval
     */
    async publishAdminProduct(requestParameters: PublishAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse> {
        const response = await this.publishAdminProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rollbackAdminProduct without sending the request
     */
    async rollbackAdminProductRequestOpts(requestParameters: RollbackAdminProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productCode'] == null) {
            throw new runtime.RequiredError(
                'productCode',
                'Required parameter "productCode" was null or undefined when calling rollbackAdminProduct().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling rollbackAdminProduct().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling rollbackAdminProduct().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling rollbackAdminProduct().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling rollbackAdminProduct().'
            );
        }

        if (requestParameters['adminProductRollbackRequest'] == null) {
            throw new runtime.RequiredError(
                'adminProductRollbackRequest',
                'Required parameter "adminProductRollbackRequest" was null or undefined when calling rollbackAdminProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/products/{productCode}/rollback`;
        urlPath = urlPath.replace('{productCode}', encodeURIComponent(String(requestParameters['productCode'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminProductRollbackRequestToJSON(requestParameters['adminProductRollbackRequest']),
        };
    }

    /**
     * Re-publish a previously published immutable version
     */
    async rollbackAdminProductRaw(requestParameters: RollbackAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>> {
        const requestOptions = await this.rollbackAdminProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminProductResponseFromJSON(jsonValue));
    }

    /**
     * Re-publish a previously published immutable version
     */
    async rollbackAdminProduct(requestParameters: RollbackAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse> {
        const response = await this.rollbackAdminProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for runAdminPaymentReconciliation without sending the request
     */
    async runAdminPaymentReconciliationRequestOpts(requestParameters: RunAdminPaymentReconciliationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling runAdminPaymentReconciliation().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling runAdminPaymentReconciliation().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling runAdminPaymentReconciliation().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling runAdminPaymentReconciliation().'
            );
        }

        if (requestParameters['paymentReconciliationRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentReconciliationRequest',
                'Required parameter "paymentReconciliationRequest" was null or undefined when calling runAdminPaymentReconciliation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/payment-reconciliations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentReconciliationRequestToJSON(requestParameters['paymentReconciliationRequest']),
        };
    }

    /**
     * Reconcile stale payment attempts and recover interrupted grants
     */
    async runAdminPaymentReconciliationRaw(requestParameters: RunAdminPaymentReconciliationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentReconciliationResponse>> {
        const requestOptions = await this.runAdminPaymentReconciliationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentReconciliationResponseFromJSON(jsonValue));
    }

    /**
     * Reconcile stale payment attempts and recover interrupted grants
     */
    async runAdminPaymentReconciliation(requestParameters: RunAdminPaymentReconciliationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentReconciliationResponse> {
        const response = await this.runAdminPaymentReconciliationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAdminProduct without sending the request
     */
    async updateAdminProductRequestOpts(requestParameters: UpdateAdminProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productVersionId'] == null) {
            throw new runtime.RequiredError(
                'productVersionId',
                'Required parameter "productVersionId" was null or undefined when calling updateAdminProduct().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling updateAdminProduct().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling updateAdminProduct().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling updateAdminProduct().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateAdminProduct().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling updateAdminProduct().'
            );
        }

        if (requestParameters['adminProductWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'adminProductWriteRequest',
                'Required parameter "adminProductWriteRequest" was null or undefined when calling updateAdminProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("adminBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/v1/products/{productVersionId}`;
        urlPath = urlPath.replace('{productVersionId}', encodeURIComponent(String(requestParameters['productVersionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AdminProductWriteRequestToJSON(requestParameters['adminProductWriteRequest']),
        };
    }

    /**
     * Replace a draft with a new immutable product version
     */
    async updateAdminProductRaw(requestParameters: UpdateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminProductResponse>> {
        const requestOptions = await this.updateAdminProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminProductResponseFromJSON(jsonValue));
    }

    /**
     * Replace a draft with a new immutable product version
     */
    async updateAdminProduct(requestParameters: UpdateAdminProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminProductResponse> {
        const response = await this.updateAdminProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateAdminEntitlementAdjustmentXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type CreateAdminEntitlementAdjustmentXPlatformEnum = typeof CreateAdminEntitlementAdjustmentXPlatformEnum[keyof typeof CreateAdminEntitlementAdjustmentXPlatformEnum];
/**
 * @export
 */
export const CreateAdminProductXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type CreateAdminProductXPlatformEnum = typeof CreateAdminProductXPlatformEnum[keyof typeof CreateAdminProductXPlatformEnum];
/**
 * @export
 */
export const DecideAdminRefundXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type DecideAdminRefundXPlatformEnum = typeof DecideAdminRefundXPlatformEnum[keyof typeof DecideAdminRefundXPlatformEnum];
/**
 * @export
 */
export const ExecuteAdminRefundXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type ExecuteAdminRefundXPlatformEnum = typeof ExecuteAdminRefundXPlatformEnum[keyof typeof ExecuteAdminRefundXPlatformEnum];
/**
 * @export
 */
export const GetAdminOrderXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type GetAdminOrderXPlatformEnum = typeof GetAdminOrderXPlatformEnum[keyof typeof GetAdminOrderXPlatformEnum];
/**
 * @export
 */
export const GetAdminProductXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type GetAdminProductXPlatformEnum = typeof GetAdminProductXPlatformEnum[keyof typeof GetAdminProductXPlatformEnum];
/**
 * @export
 */
export const GetAdminRefundXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type GetAdminRefundXPlatformEnum = typeof GetAdminRefundXPlatformEnum[keyof typeof GetAdminRefundXPlatformEnum];
/**
 * @export
 */
export const ListAdminOrdersXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type ListAdminOrdersXPlatformEnum = typeof ListAdminOrdersXPlatformEnum[keyof typeof ListAdminOrdersXPlatformEnum];
/**
 * @export
 */
export const ListAdminProductsXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type ListAdminProductsXPlatformEnum = typeof ListAdminProductsXPlatformEnum[keyof typeof ListAdminProductsXPlatformEnum];
/**
 * @export
 */
export const ListAdminRefundsXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type ListAdminRefundsXPlatformEnum = typeof ListAdminRefundsXPlatformEnum[keyof typeof ListAdminRefundsXPlatformEnum];
/**
 * @export
 */
export const PublishAdminProductXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type PublishAdminProductXPlatformEnum = typeof PublishAdminProductXPlatformEnum[keyof typeof PublishAdminProductXPlatformEnum];
/**
 * @export
 */
export const RollbackAdminProductXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type RollbackAdminProductXPlatformEnum = typeof RollbackAdminProductXPlatformEnum[keyof typeof RollbackAdminProductXPlatformEnum];
/**
 * @export
 */
export const RunAdminPaymentReconciliationXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type RunAdminPaymentReconciliationXPlatformEnum = typeof RunAdminPaymentReconciliationXPlatformEnum[keyof typeof RunAdminPaymentReconciliationXPlatformEnum];
/**
 * @export
 */
export const UpdateAdminProductXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type UpdateAdminProductXPlatformEnum = typeof UpdateAdminProductXPlatformEnum[keyof typeof UpdateAdminProductXPlatformEnum];
