/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AuthChannelPolicyResponse,
    AuthChannelPolicyResponseFromJSON,
    AuthChannelPolicyResponseToJSON,
} from '../models/AuthChannelPolicyResponse';
import {
    type EmailChallengeResponse,
    EmailChallengeResponseFromJSON,
    EmailChallengeResponseToJSON,
} from '../models/EmailChallengeResponse';
import {
    type EmailLoginRequest,
    EmailLoginRequestFromJSON,
    EmailLoginRequestToJSON,
} from '../models/EmailLoginRequest';
import {
    type EmailSendRequest,
    EmailSendRequestFromJSON,
    EmailSendRequestToJSON,
} from '../models/EmailSendRequest';
import {
    type EmptyResponse,
    EmptyResponseFromJSON,
    EmptyResponseToJSON,
} from '../models/EmptyResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type LoginResponse,
    LoginResponseFromJSON,
    LoginResponseToJSON,
} from '../models/LoginResponse';
import {
    type RefreshRequest,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
} from '../models/RefreshRequest';
import {
    type SmsChallengeResponse,
    SmsChallengeResponseFromJSON,
    SmsChallengeResponseToJSON,
} from '../models/SmsChallengeResponse';
import {
    type SmsLoginRequest,
    SmsLoginRequestFromJSON,
    SmsLoginRequestToJSON,
} from '../models/SmsLoginRequest';
import {
    type SmsSendRequest,
    SmsSendRequestFromJSON,
    SmsSendRequestToJSON,
} from '../models/SmsSendRequest';
import {
    type TokenResponse,
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/TokenResponse';

export interface GetAuthChannelsRequest {
    xClientVersion: string;
    xPlatform: GetAuthChannelsXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    xRequestId?: string;
}

export interface LoginWithEmailRequest {
    xClientVersion: string;
    xPlatform: LoginWithEmailXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    emailLoginRequest: EmailLoginRequest;
    xRequestId?: string;
}

export interface LoginWithSmsRequest {
    xClientVersion: string;
    xPlatform: LoginWithSmsXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    smsLoginRequest: SmsLoginRequest;
    xRequestId?: string;
}

export interface LogoutAllDevicesRequest {
    xClientVersion: string;
    xPlatform: LogoutAllDevicesXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    xRequestId?: string;
}

export interface LogoutCurrentDeviceRequest {
    xClientVersion: string;
    xPlatform: LogoutCurrentDeviceXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    xRequestId?: string;
}

export interface RefreshAccessTokenRequest {
    xClientVersion: string;
    xPlatform: RefreshAccessTokenXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    refreshRequest: RefreshRequest;
    xRequestId?: string;
}

export interface SendEmailChallengeRequest {
    xClientVersion: string;
    xPlatform: SendEmailChallengeXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    emailSendRequest: EmailSendRequest;
    xRequestId?: string;
}

export interface SendSmsChallengeRequest {
    xClientVersion: string;
    xPlatform: SendSmsChallengeXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    smsSendRequest: SmsSendRequest;
    xRequestId?: string;
}

/**
 * AUTHApi - interface
 *
 * @export
 * @interface AUTHApiInterface
 */
export interface AUTHApiInterface {
    /**
     * Creates request options for getAuthChannels without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    getAuthChannelsRequestOpts(requestParameters: GetAuthChannelsRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns server-authoritative channel order and availability. Clients use EMAIL as their safe default if this request is unavailable and never infer account existence from channel availability.
     * @summary Read the public authentication channel policy
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    getAuthChannelsRaw(requestParameters: GetAuthChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthChannelPolicyResponse>>;

    /**
     * Returns server-authoritative channel order and availability. Clients use EMAIL as their safe default if this request is unavailable and never infer account existence from channel availability.
     * Read the public authentication channel policy
     */
    getAuthChannels(requestParameters: GetAuthChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthChannelPolicyResponse>;

    /**
     * Creates request options for loginWithEmail without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {EmailLoginRequest} emailLoginRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    loginWithEmailRequestOpts(requestParameters: LoginWithEmailRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Login or register with a verified email challenge
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {EmailLoginRequest} emailLoginRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    loginWithEmailRaw(requestParameters: LoginWithEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>>;

    /**
     * Login or register with a verified email challenge
     */
    loginWithEmail(requestParameters: LoginWithEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse>;

    /**
     * Creates request options for loginWithSms without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {SmsLoginRequest} smsLoginRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    loginWithSmsRequestOpts(requestParameters: LoginWithSmsRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Login or register with a verified SMS challenge
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {SmsLoginRequest} smsLoginRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    loginWithSmsRaw(requestParameters: LoginWithSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>>;

    /**
     * Login or register with a verified SMS challenge
     */
    loginWithSms(requestParameters: LoginWithSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse>;

    /**
     * Creates request options for logoutAllDevices without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    logoutAllDevicesRequestOpts(requestParameters: LogoutAllDevicesRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Revoke all sessions for the current user
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    logoutAllDevicesRaw(requestParameters: LogoutAllDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmptyResponse>>;

    /**
     * Revoke all sessions for the current user
     */
    logoutAllDevices(requestParameters: LogoutAllDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmptyResponse>;

    /**
     * Creates request options for logoutCurrentDevice without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    logoutCurrentDeviceRequestOpts(requestParameters: LogoutCurrentDeviceRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Revoke the current device session
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    logoutCurrentDeviceRaw(requestParameters: LogoutCurrentDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmptyResponse>>;

    /**
     * Revoke the current device session
     */
    logoutCurrentDevice(requestParameters: LogoutCurrentDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmptyResponse>;

    /**
     * Creates request options for refreshAccessToken without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {RefreshRequest} refreshRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    refreshAccessTokenRequestOpts(requestParameters: RefreshAccessTokenRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Rotate a refresh token
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {RefreshRequest} refreshRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    refreshAccessTokenRaw(requestParameters: RefreshAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>>;

    /**
     * Rotate a refresh token
     */
    refreshAccessToken(requestParameters: RefreshAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse>;

    /**
     * Creates request options for sendEmailChallenge without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {EmailSendRequest} emailSendRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    sendEmailChallengeRequestOpts(requestParameters: SendEmailChallengeRequest): Promise<runtime.RequestOpts>;

    /**
     * The response is indistinguishable for existing and new email addresses. Provider details and account existence are never disclosed.
     * @summary Send a passwordless email login code
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {EmailSendRequest} emailSendRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    sendEmailChallengeRaw(requestParameters: SendEmailChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailChallengeResponse>>;

    /**
     * The response is indistinguishable for existing and new email addresses. Provider details and account existence are never disclosed.
     * Send a passwordless email login code
     */
    sendEmailChallenge(requestParameters: SendEmailChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailChallengeResponse>;

    /**
     * Creates request options for sendSmsChallenge without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {SmsSendRequest} smsSendRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    sendSmsChallengeRequestOpts(requestParameters: SendSmsChallengeRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Send a login verification code
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {SmsSendRequest} smsSendRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AUTHApiInterface
     */
    sendSmsChallengeRaw(requestParameters: SendSmsChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsChallengeResponse>>;

    /**
     * Send a login verification code
     */
    sendSmsChallenge(requestParameters: SendSmsChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsChallengeResponse>;

}

/**
 *
 */
export class AUTHApi extends runtime.BaseAPI implements AUTHApiInterface {

    /**
     * Creates request options for getAuthChannels without sending the request
     */
    async getAuthChannelsRequestOpts(requestParameters: GetAuthChannelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling getAuthChannels().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling getAuthChannels().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling getAuthChannels().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling getAuthChannels().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }


        let urlPath = `/v1/auth/channels`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns server-authoritative channel order and availability. Clients use EMAIL as their safe default if this request is unavailable and never infer account existence from channel availability.
     * Read the public authentication channel policy
     */
    async getAuthChannelsRaw(requestParameters: GetAuthChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthChannelPolicyResponse>> {
        const requestOptions = await this.getAuthChannelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthChannelPolicyResponseFromJSON(jsonValue));
    }

    /**
     * Returns server-authoritative channel order and availability. Clients use EMAIL as their safe default if this request is unavailable and never infer account existence from channel availability.
     * Read the public authentication channel policy
     */
    async getAuthChannels(requestParameters: GetAuthChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthChannelPolicyResponse> {
        const response = await this.getAuthChannelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWithEmail without sending the request
     */
    async loginWithEmailRequestOpts(requestParameters: LoginWithEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling loginWithEmail().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling loginWithEmail().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling loginWithEmail().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling loginWithEmail().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling loginWithEmail().'
            );
        }

        if (requestParameters['emailLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'emailLoginRequest',
                'Required parameter "emailLoginRequest" was null or undefined when calling loginWithEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v1/auth/email/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailLoginRequestToJSON(requestParameters['emailLoginRequest']),
        };
    }

    /**
     * Login or register with a verified email challenge
     */
    async loginWithEmailRaw(requestParameters: LoginWithEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        const requestOptions = await this.loginWithEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
    }

    /**
     * Login or register with a verified email challenge
     */
    async loginWithEmail(requestParameters: LoginWithEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.loginWithEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWithSms without sending the request
     */
    async loginWithSmsRequestOpts(requestParameters: LoginWithSmsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling loginWithSms().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling loginWithSms().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling loginWithSms().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling loginWithSms().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling loginWithSms().'
            );
        }

        if (requestParameters['smsLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'smsLoginRequest',
                'Required parameter "smsLoginRequest" was null or undefined when calling loginWithSms().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v1/auth/sms/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SmsLoginRequestToJSON(requestParameters['smsLoginRequest']),
        };
    }

    /**
     * Login or register with a verified SMS challenge
     */
    async loginWithSmsRaw(requestParameters: LoginWithSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        const requestOptions = await this.loginWithSmsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
    }

    /**
     * Login or register with a verified SMS challenge
     */
    async loginWithSms(requestParameters: LoginWithSmsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.loginWithSmsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logoutAllDevices without sending the request
     */
    async logoutAllDevicesRequestOpts(requestParameters: LogoutAllDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling logoutAllDevices().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling logoutAllDevices().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling logoutAllDevices().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling logoutAllDevices().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling logoutAllDevices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/logout-all`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke all sessions for the current user
     */
    async logoutAllDevicesRaw(requestParameters: LogoutAllDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmptyResponse>> {
        const requestOptions = await this.logoutAllDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmptyResponseFromJSON(jsonValue));
    }

    /**
     * Revoke all sessions for the current user
     */
    async logoutAllDevices(requestParameters: LogoutAllDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmptyResponse> {
        const response = await this.logoutAllDevicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logoutCurrentDevice without sending the request
     */
    async logoutCurrentDeviceRequestOpts(requestParameters: LogoutCurrentDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling logoutCurrentDevice().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling logoutCurrentDevice().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling logoutCurrentDevice().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling logoutCurrentDevice().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling logoutCurrentDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke the current device session
     */
    async logoutCurrentDeviceRaw(requestParameters: LogoutCurrentDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmptyResponse>> {
        const requestOptions = await this.logoutCurrentDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmptyResponseFromJSON(jsonValue));
    }

    /**
     * Revoke the current device session
     */
    async logoutCurrentDevice(requestParameters: LogoutCurrentDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmptyResponse> {
        const response = await this.logoutCurrentDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshAccessToken without sending the request
     */
    async refreshAccessTokenRequestOpts(requestParameters: RefreshAccessTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling refreshAccessToken().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling refreshAccessToken().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling refreshAccessToken().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling refreshAccessToken().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling refreshAccessToken().'
            );
        }

        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling refreshAccessToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v1/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        };
    }

    /**
     * Rotate a refresh token
     */
    async refreshAccessTokenRaw(requestParameters: RefreshAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.refreshAccessTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Rotate a refresh token
     */
    async refreshAccessToken(requestParameters: RefreshAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.refreshAccessTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmailChallenge without sending the request
     */
    async sendEmailChallengeRequestOpts(requestParameters: SendEmailChallengeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling sendEmailChallenge().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling sendEmailChallenge().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling sendEmailChallenge().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling sendEmailChallenge().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling sendEmailChallenge().'
            );
        }

        if (requestParameters['emailSendRequest'] == null) {
            throw new runtime.RequiredError(
                'emailSendRequest',
                'Required parameter "emailSendRequest" was null or undefined when calling sendEmailChallenge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v1/auth/email/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailSendRequestToJSON(requestParameters['emailSendRequest']),
        };
    }

    /**
     * The response is indistinguishable for existing and new email addresses. Provider details and account existence are never disclosed.
     * Send a passwordless email login code
     */
    async sendEmailChallengeRaw(requestParameters: SendEmailChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailChallengeResponse>> {
        const requestOptions = await this.sendEmailChallengeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailChallengeResponseFromJSON(jsonValue));
    }

    /**
     * The response is indistinguishable for existing and new email addresses. Provider details and account existence are never disclosed.
     * Send a passwordless email login code
     */
    async sendEmailChallenge(requestParameters: SendEmailChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailChallengeResponse> {
        const response = await this.sendEmailChallengeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendSmsChallenge without sending the request
     */
    async sendSmsChallengeRequestOpts(requestParameters: SendSmsChallengeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling sendSmsChallenge().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling sendSmsChallenge().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling sendSmsChallenge().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling sendSmsChallenge().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling sendSmsChallenge().'
            );
        }

        if (requestParameters['smsSendRequest'] == null) {
            throw new runtime.RequiredError(
                'smsSendRequest',
                'Required parameter "smsSendRequest" was null or undefined when calling sendSmsChallenge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/v1/auth/sms/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SmsSendRequestToJSON(requestParameters['smsSendRequest']),
        };
    }

    /**
     * Send a login verification code
     */
    async sendSmsChallengeRaw(requestParameters: SendSmsChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsChallengeResponse>> {
        const requestOptions = await this.sendSmsChallengeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsChallengeResponseFromJSON(jsonValue));
    }

    /**
     * Send a login verification code
     */
    async sendSmsChallenge(requestParameters: SendSmsChallengeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsChallengeResponse> {
        const response = await this.sendSmsChallengeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAuthChannelsXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type GetAuthChannelsXPlatformEnum = typeof GetAuthChannelsXPlatformEnum[keyof typeof GetAuthChannelsXPlatformEnum];
/**
 * @export
 */
export const LoginWithEmailXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type LoginWithEmailXPlatformEnum = typeof LoginWithEmailXPlatformEnum[keyof typeof LoginWithEmailXPlatformEnum];
/**
 * @export
 */
export const LoginWithSmsXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type LoginWithSmsXPlatformEnum = typeof LoginWithSmsXPlatformEnum[keyof typeof LoginWithSmsXPlatformEnum];
/**
 * @export
 */
export const LogoutAllDevicesXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type LogoutAllDevicesXPlatformEnum = typeof LogoutAllDevicesXPlatformEnum[keyof typeof LogoutAllDevicesXPlatformEnum];
/**
 * @export
 */
export const LogoutCurrentDeviceXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type LogoutCurrentDeviceXPlatformEnum = typeof LogoutCurrentDeviceXPlatformEnum[keyof typeof LogoutCurrentDeviceXPlatformEnum];
/**
 * @export
 */
export const RefreshAccessTokenXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type RefreshAccessTokenXPlatformEnum = typeof RefreshAccessTokenXPlatformEnum[keyof typeof RefreshAccessTokenXPlatformEnum];
/**
 * @export
 */
export const SendEmailChallengeXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type SendEmailChallengeXPlatformEnum = typeof SendEmailChallengeXPlatformEnum[keyof typeof SendEmailChallengeXPlatformEnum];
/**
 * @export
 */
export const SendSmsChallengeXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type SendSmsChallengeXPlatformEnum = typeof SendSmsChallengeXPlatformEnum[keyof typeof SendSmsChallengeXPlatformEnum];
