/* tslint:disable */
/* eslint-disable */
/**
 * Love Reply Assistant API
 * Contract-first API for Android, administration, workers, and provider integrations. Public wire fields use lowerCamelCase and all timestamps use RFC 3339 UTC.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateRefundRequest,
    CreateRefundRequestFromJSON,
    CreateRefundRequestToJSON,
} from '../models/CreateRefundRequest';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type RefundResponse,
    RefundResponseFromJSON,
    RefundResponseToJSON,
} from '../models/RefundResponse';

export interface CreateRefundOperationRequest {
    xClientVersion: string;
    xPlatform: CreateRefundOperationXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    idempotencyKey: string;
    createRefundRequest: CreateRefundRequest;
    xRequestId?: string;
}

export interface GetRefundRequest {
    refundId: string;
    xClientVersion: string;
    xPlatform: GetRefundXPlatformEnum;
    xDeviceId: string;
    acceptLanguage: string;
    xRequestId?: string;
}

/**
 * REFUNDApi - interface
 *
 * @export
 * @interface REFUNDApiInterface
 */
export interface REFUNDApiInterface {
    /**
     * Creates request options for createRefund without sending the request
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {CreateRefundRequest} createRefundRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof REFUNDApiInterface
     */
    createRefundRequestOpts(requestParameters: CreateRefundOperationRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Request a full or partial refund
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} idempotencyKey Unique key scoped to authenticated actor, operation, and request fingerprint.
     * @param {CreateRefundRequest} createRefundRequest
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof REFUNDApiInterface
     */
    createRefundRaw(requestParameters: CreateRefundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefundResponse>>;

    /**
     * Request a full or partial refund
     */
    createRefund(requestParameters: CreateRefundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundResponse>;

    /**
     * Creates request options for getRefund without sending the request
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @throws {RequiredError}
     * @memberof REFUNDApiInterface
     */
    getRefundRequestOpts(requestParameters: GetRefundRequest): Promise<runtime.RequestOpts>;

    /**
     *
     * @summary Read an owned refund and entitlement recovery state
     * @param {string} refundId
     * @param {string} xClientVersion Semantic application version used for compatibility enforcement.
     * @param {'ANDROID' | 'ADMIN_WEB'} xPlatform
     * @param {string} xDeviceId Opaque installation ID. It is not an authentication credential.
     * @param {string} acceptLanguage
     * @param {string} [xRequestId] Client correlation ID. The server returns the final accepted value.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof REFUNDApiInterface
     */
    getRefundRaw(requestParameters: GetRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefundResponse>>;

    /**
     * Read an owned refund and entitlement recovery state
     */
    getRefund(requestParameters: GetRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundResponse>;

}

/**
 *
 */
export class REFUNDApi extends runtime.BaseAPI implements REFUNDApiInterface {

    /**
     * Creates request options for createRefund without sending the request
     */
    async createRefundRequestOpts(requestParameters: CreateRefundOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling createRefund().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling createRefund().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling createRefund().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling createRefund().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createRefund().'
            );
        }

        if (requestParameters['createRefundRequest'] == null) {
            throw new runtime.RequiredError(
                'createRefundRequest',
                'Required parameter "createRefundRequest" was null or undefined when calling createRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/refunds`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRefundRequestToJSON(requestParameters['createRefundRequest']),
        };
    }

    /**
     * Request a full or partial refund
     */
    async createRefundRaw(requestParameters: CreateRefundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefundResponse>> {
        const requestOptions = await this.createRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundResponseFromJSON(jsonValue));
    }

    /**
     * Request a full or partial refund
     */
    async createRefund(requestParameters: CreateRefundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundResponse> {
        const response = await this.createRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRefund without sending the request
     */
    async getRefundRequestOpts(requestParameters: GetRefundRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refundId'] == null) {
            throw new runtime.RequiredError(
                'refundId',
                'Required parameter "refundId" was null or undefined when calling getRefund().'
            );
        }

        if (requestParameters['xClientVersion'] == null) {
            throw new runtime.RequiredError(
                'xClientVersion',
                'Required parameter "xClientVersion" was null or undefined when calling getRefund().'
            );
        }

        if (requestParameters['xPlatform'] == null) {
            throw new runtime.RequiredError(
                'xPlatform',
                'Required parameter "xPlatform" was null or undefined when calling getRefund().'
            );
        }

        if (requestParameters['xDeviceId'] == null) {
            throw new runtime.RequiredError(
                'xDeviceId',
                'Required parameter "xDeviceId" was null or undefined when calling getRefund().'
            );
        }

        if (requestParameters['acceptLanguage'] == null) {
            throw new runtime.RequiredError(
                'acceptLanguage',
                'Required parameter "acceptLanguage" was null or undefined when calling getRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xRequestId'] != null) {
            headerParameters['X-Request-Id'] = String(requestParameters['xRequestId']);
        }

        if (requestParameters['xClientVersion'] != null) {
            headerParameters['X-Client-Version'] = String(requestParameters['xClientVersion']);
        }

        if (requestParameters['xPlatform'] != null) {
            headerParameters['X-Platform'] = String(requestParameters['xPlatform']);
        }

        if (requestParameters['xDeviceId'] != null) {
            headerParameters['X-Device-Id'] = String(requestParameters['xDeviceId']);
        }

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/refunds/{refundId}`;
        urlPath = urlPath.replace('{refundId}', encodeURIComponent(String(requestParameters['refundId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read an owned refund and entitlement recovery state
     */
    async getRefundRaw(requestParameters: GetRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefundResponse>> {
        const requestOptions = await this.getRefundRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundResponseFromJSON(jsonValue));
    }

    /**
     * Read an owned refund and entitlement recovery state
     */
    async getRefund(requestParameters: GetRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundResponse> {
        const response = await this.getRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CreateRefundOperationXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type CreateRefundOperationXPlatformEnum = typeof CreateRefundOperationXPlatformEnum[keyof typeof CreateRefundOperationXPlatformEnum];
/**
 * @export
 */
export const GetRefundXPlatformEnum = {
    Android: 'ANDROID',
    AdminWeb: 'ADMIN_WEB'
} as const;
export type GetRefundXPlatformEnum = typeof GetRefundXPlatformEnum[keyof typeof GetRefundXPlatformEnum];
